### ISSUE TITLE
it DOES NOT deploy correct path on osx reliably

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/install-scripts#100]
---
**Issue moved from dotnet/core#5402**
- Please respond to @Hardcore-fs.

---

_From @Hardcore-fs on Tuesday, October 20, 2020 9:22:06 PM_

after running install ,the files are in teh location expected

but issuing the "dotnet" command at a teminal

$dotnet
bash: dotnet: command not found

**Comment by carlossanlop** [comment]
---
**Issue moved from dotnet/core#5402**
- Please respond to @carlossanlop.

---

_From @carlossanlop on Wednesday, October 21, 2020 10:58:10 PM_

Did you close and reopen the command line terminal after installation?

**Comment by carlossanlop** [comment]
---
**Issue moved from dotnet/core#5402**
- Please respond to @Hardcore-fs.

---

_From @Hardcore-fs on Thursday, October 22, 2020 11:46:23 AM_

Yep.....
I found it !!!!!!
it is how you deal with adding the path to the bash script..., sometimes it completely fails to append the script
so of course it cannot work., nothing to do with the terminal...
after manually modifying the script it is fixed...

I strongly suspect it is down to "GPG suite" on mac ,since that's the last entry on the bash script.


i added the following at the end of the .bash_profile:


#Microsoft dotnet
PATH="/usr/local/share/dotnet:${PATH}"
export PATH

**Comment by carlossanlop** [comment]
---
**Issue moved from dotnet/core#5402**
- Please respond to @carlossanlop.

---

_From @carlossanlop on Thursday, October 22, 2020 6:34:00 PM_

Thanks for taking a deeper look, @Hardcore-fs 

@wli3 @dsplaisted is this something we should look into on our side?

**Comment by carlossanlop** [comment]
---
**Issue moved from dotnet/core#5402**
- Please respond to @Hardcore-fs.

---

_From @Hardcore-fs on Thursday, October 22, 2020 11:45:55 PM_

it was installed by downloading the MS installer from the web site.
But i also think their 3.X installer suffers the SAME problem.

because i tried the 3.x first & it worked on some machines, but not others
then i tried the 5.x and the same result...

once the fix was in , it has been solid for days...

**Comment by carlossanlop** [comment]
---
**Issue moved from dotnet/core#5402**
- Please respond to @carlossanlop.

---

_From @carlossanlop on Friday, November 6, 2020 7:10:34 PM_

@dsplaisted I'll move it to that repo so we don't lose track of a potential bug.

**Comment by bozturkMSFT** [comment]
This doesn't seem to be related to install scripts and it is being tracked here https://github.com/dotnet/core/issues/5402 .
Let us know if you think this should be reopened.

**Comment by Hardcore-fs** [comment]
it would relate to BOTH.....

Clearly during running the INSTALLER , something goes wrong with the INSTALL SCRIPT!!!
since i don't know WHAT the installer is supposed to shove into the install script, a judgement cannot be made.
