### ISSUE TITLE
When is https://dot.net/v1/dotnet-install.sh updated?

### ISSUE THREAD

**Issue by 0xced** [dotnet/install-scripts#101]
Today I struggled with the `dotnet-install.sh` script when using the `--jsonfile` option and multiple entries in the `sdk` object of my `global.json` file.

This issue has already been addressed by #90 two weeks ago. When will the [officially recommended](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#recommended-version) script at https://dot.net/v1/dotnet-install.sh include this fix?

I'm now using https://raw.githubusercontent.com/dotnet/install-scripts/03a51b2ad0d57fddb15af1ccbc041c383ec53669/src/dotnet-install.sh instead of https://dot.net/v1/dotnet-install.sh but that's a bit cumbersome.

**Comment by bozturkMSFT** [comment]
Hi @0xced ,
 `dot.net` website doesn't automatically pickup the changes we merge into master, so we deploy the files manually depending on the urgency of the changes.
 The change you mentioned #90 should be available from `dot.net` website sometime this week. I will let you know here when that happens.

**Comment by bozturkMSFT** [comment]
Hi @0xced ,
 Changes are now available at https://dot.net/v1/dotnet-install.sh

**Comment by 0xced** [comment]
Thanks for the update, Bekir!
