### ISSUE TITLE
.Net 5.0 fails to download

### ISSUE THREAD

**Issue by Swoorup** [dotnet/install-scripts#105]
The script still downloads the 3.1.404 even with current channel? 

```
~/bin on ☁️  apmproduction(ap-southeast-2) took 4s
❯ ./dotnet-install.sh -c Current -v latest                                                                    15:10:16
dotnet-install: .NET Core SDK version 3.1.404 is already installed.
dotnet-install: Adding to current process PATH: `/Users/swoorup.joshi/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
```

**Comment by 7sDream** [comment]
And use `--version 5.0` will get a 404 error.

(2020-11-12 16.09 UTC+8)

**Comment by kengibous** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/Current/latest.version
Returns -
33d643ff75d18c2991a3588d9989a0951ce86438
3.1.404

https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/Current/latest.version
Returns -
371a26f07b23ad77c636332c2dfc0cbd1d8137ba
5.0.0

https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0/latest.version
HTTP 404

https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/5.0/latest.version
HTTP 404

**Comment by Swoorup** [comment]
This now works for me.

**Comment by ektrah** [comment]
For me, channel `Current` works, but `5.0` doesn't.

**Comment by kengibous** [comment]
> This now works for me.

@Swoorup what works? **5.0**, does not.  I think that 5.0 should work as well and that issue should not be closed currently.

**Comment by Swoorup** [comment]
@kengibous It works with `dotnet-install.sh -c Current` for me.

![image](https://user-images.githubusercontent.com/3408009/99258395-9bc6ad00-286c-11eb-9267-cf4b1d787940.png)

**Comment by kengibous** [comment]
@Swoorup shouldn't a 5.0 version be available as well?  2.1 and 3.1 work for example.

https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.1/latest.version - Works
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0/latest.version - Does not work

**Comment by Swoorup** [comment]
Hmm, perhaps that should work as well. 

Not just `https://dotnetcli.blob.core.windows.net/dotnet/Sdk/Current/latest.version`

Reopening.

**Comment by bozturkMSFT** [comment]
@mmitche Could you drop some info on this? Feed doesn't seem to have a folder `5.0` like it did for `3.1`.

**Comment by mmitche** [comment]
@bozturkMSFT This looks like it's manually updated on release day. Also the version file has a sha from the wrong repo (though the version is correct).

I'm guessing that @rbhanda knows more about the automation that updates this.

**Comment by rbhanda** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/Current/latest.version  & https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0/latest.version are now updated with the commit from dotnet/installer repo

**Comment by mmitche** [comment]
> And use `--version 5.0` will get a 404 error.
> 
> (2020-11-12 16.09 UTC+8)

@7sDream @bozturkMSFT This is an odd invocation. there isn't really a "5.0" sdk, since there are multiple SDKs per runtime. We can sort of say "latest 5.0 SDK" and have it mean something (the latest version of the newest band of the 5.0), but if you want an explicit version, --version should be passed "5.0.100".

**Comment by 7sDream** [comment]
@mmitche 

You are right. I read the docs again, and it says `--version` requires three digits, while `--channel` requires two. 

Thank you!

**Comment by bozturkMSFT** [comment]
Issue should be resolved now. Please comment/reopen if `-channel 5.0` doesn't work for you.

**Comment by JelleHissink** [comment]
```
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --install-dir /dotnet --channel 5.0 --runtime aspnetcore
```
Still results in 
```
curl: (22) The requested URL returned error: 404 The specified blob does not exist.
```

Regards

**Comment by kengibous** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/5.0/latest.version - still http 404

**Comment by rbhanda** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/5.0/latest.version should be available now

**Comment by kengibous** [comment]
looks good now, thank you everyone

**Comment by bozturkMSFT** [comment]
@rbhanda Can you also fix this for the other supported runtime values "dotnet" and "windowsdesktop"?

**Comment by wjk** [comment]
The `install-dotnet.ps1` script is still completely broken and unusable. I am using the latest version of this script, and no matter what parameters I pass (`-Channel` or `-Version`), what version number format I use (I’ve tried `5.0` and `5.0.100`), or what download I select (core runtime or windows-desktop), it still 404s and fails. Every. Single. Time. This is breaking my CI build, and is driving me crazy. Could someone look into this please? Thanks!

**Comment by mmitche** [comment]
@rbhanda There is a missing 5.0 channel for Runtime and WindowsDesktop. How are these updated today on release day?

`.\.dotnet\dotnet-install.ps1 -Runtime dotnet -Version 5.0.0` will work for the core runtime. Version always expected "major.minor.patch" as 5.0 is could refer to any version in 5.0.*

Alternatively just plain .\.dotnet\dotnet-install.ps1 -Version 5.0.100

@bozturkMSFT The windowsdesktop runtime is not correctly being resolved in 5.0. In 5.0 it moved out of the core-setup repo and stopped being dropped under the core runtime directory (it's under https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/5.0.0/windowsdesktop-runtime-5.0.0-win-x64.msi) vs. https://dotnetcli.blob.core.windows.net/dotnet/Runtime/5.0.0/windowsdesktop-runtime-5.0.0-win-x64.msi) and thus is now aligned with AspNetCore.

We need to update dotnet-install to look for this in the right place. Probably with some fallback logic too.

**Comment by rbhanda** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/5.0/latest.version
https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/5.0/latest.version

Both Runtime and WindowsDesktop are now updated

**Comment by bozturkMSFT** [comment]
@mmitche Since which version do we have the windowsdesktop under runtime directory? I'm trying to figure out how the fallback would work. As you know, there is no version checking in the script. We try a download link, if it fails, we try the other. It would be nice if we could avoid that in this scenario.

**Comment by mmitche** [comment]
> @mmitche Since which version do we have the windowsdesktop under runtime directory? I'm trying to figure out how the fallback would work. As you know, there is no version checking in the script. We try a download link, if it fails, we try the other. It would be nice if we could avoid that in this scenario.

3.1. We could maybe also do something where we go and fixup 3.1's layout to be compliant with the 5.0 layout.

**Comment by bozturkMSFT** [comment]
The issue with downloading the windows desktop runtime is tracked in issue https://github.com/dotnet/install-scripts/issues/116.
Closing this one.
