### ISSUE TITLE
Add support for aka.ms links for dotnet-install

### ISSUE THREAD

**Issue by mmitche** [dotnet/install-scripts#12]
Add support for the aka.ms links to dotnet-install so that we can remove the copy to latest in various repositories. dotnet-install should, either as the primary method, or a backup, attempt to use the aka.ms links as a method of getting at the latest installers for a specific channel.

aka.ms links have been designed to place the link to a specific blob under a predictable url:

```
aka.ms/dotnet/net5/dev/Sdk/dotnet-sdk-win-x86.exe
aka.ms/dotnet/<channel>/Sdk/dotnet-sdk-win-x86.exe
```

The version information has been removed.

Currently, the one hiccup here is that we don't have a version file to know whether the latest version may already be installed. This should be implemented with: https://github.com/dotnet/core-sdk/issues/5554 (similar entries exist in windowsdesktop, runtime, and aspnetcore). This version file could simply be published alongside the rest of the blobs.

**Comment by wli3** [comment]
@bozturkMSFT SDK team should do this?

**Comment by wli3** [comment]
@bozturkMSFT any update? schedule?

**Comment by bozturkMSFT** [comment]
I am currently working on the signing of the scripts #14 .
What is the priority of the issue that is being blocked?

**Comment by wli3** [comment]
It is relatively high priority. Considering "avoid updating copy_to_latest dependsOn every time a new branch is created" can save several hours every month.

**Comment by donJoseLuis** [comment]
@wli3 , we'll plan this work for the week of June 1st.

**Comment by wli3** [comment]
Any progress on this?

**Comment by bozturkMSFT** [comment]
Issues tracking the version information:
- WindowsDesktop https://github.com/dotnet/windowsdesktop/issues/776
- Runtime https://github.com/dotnet/runtime/issues/3833
- AspNetCore https://github.com/dotnet/aspnetcore/issues/16859

**Comment by wli3** [comment]
Looks no progress. But i'll ping this thread after September

**Comment by wli3** [comment]
@bozturkMSFT may update?

**Comment by vlada-shubina** [comment]
Related link implementation tickets:
https://github.com/dotnet/arcade/issues/6641
https://github.com/dotnet/arcade/issues/6642
https://github.com/dotnet/arcade/issues/6643

**Comment by bozturkMSFT** [comment]
I'm putting this on-hold until ES can complete the tasks on their end. @mmitche Please let us know when you have some progress on your end.

**Comment by bozturkMSFT** [comment]
Before this is merged, the docs should be updated according to the new changes.
