### ISSUE TITLE
Update docs.microsoft.com for latest changes

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/install-scripts#122]
Update documentation before publishing latest changes to website:
Documentation page: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

https://github.com/dotnet/install-scripts/pull/118
- deprecate `--runtime-id`
- add `--os`

**Comment by bozturkMSFT** [comment]
Update features brought by aka.ms links: quality option, for instance.

**Comment by bozturkMSFT** [comment]
Related changes regarding --runtime-id and --os  options are proposed in PR https://github.com/dotnet/docs/pull/22453

**Comment by bozturkMSFT** [comment]
Related PR is now merged. Closing this since aka.ms link issue #12  is on hold at the moment.
