### ISSUE TITLE
Runtime packages are not published to branch channels though should

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/install-scripts#124]
SDK still keeps updated the branch channels: master, release/<version>.  `latest.version` files seems to be regularly updated.

Runtime doesn't update those channels. 
- "release/5.0" is absent for dotnet
- "release/3.0", "release/3.1", "release/5.0" are absent for aspnetcore
Other branch channels are present however are not updated since Nov 2019.

Decide whether these channels have to be maintained and act upon
- if they have to be maintained, once publishing is resumed the tests should be enabled
- if they are deprecated, update install scripts documentation to reflect this.

_Originally posted by @vlada-shubina in https://github.com/dotnet/install-scripts/pull/123#discussion_r543215939_

**Comment by vlada-shubina** [comment]
@mmitche @wtgodbe  @rbhanda I moved the conversation out of the original PR for better tracking.

**Comment by bozturkMSFT** [comment]
The task is moved to ADO https://devdiv.visualstudio.com/DevDiv/_queries/edit/1262275
Closing this.
