### ISSUE TITLE
Install scripts may fail when TERM is not set.

### ISSUE THREAD

**Issue by tmds** [dotnet/install-scripts#125]
I ran the install script in a `centos:8` container which doesn't have the TERM envvar set and it failed with:

```
tput: No value for $TERM and no -T specified
Failed to install dotnet SDK from public location (exit code '2').
Failed to install dotnet SDK from public location (exit code '2').
```

**Comment by bozturkMSFT** [comment]
Hey @tmds,
 Can you let me know how you are impacted by this? Is this an ongoing incident? Can you workaround by setting the TERM yourself?

**Comment by tmds** [comment]
> Can you workaround by setting the TERM yourself?

Yes.

**Comment by bozturkMSFT** [comment]
Hi @tmds,
 I am glad to hear that you have a workaround to unblock you. I will close this since it seems to be a system configuration issue rather than an install script issue.
 Let us know if you need further help with this.

**Comment by bozturkMSFT** [comment]
This was fixed in https://github.com/dotnet/install-scripts/pull/154 and will be available in the website after the deployment.
