### ISSUE TITLE
dotnet-install.sh: line 908: http_code: unbound variable error

### ISSUE THREAD

**Issue by onurvatan** [dotnet/install-scripts#138]
Hi,

After this commit https://github.com/dotnet/install-scripts/commit/1f7ced318c54572ca2d90fc619739deb0b9d405b#diff-328f65c23ac5e22ef0b28e2cc343f85c360184e84bb3fbfcf01bec19fea43c6e

We have that error on the Jenkins pipeline like below. Please check this issue. Thanks.

/home/jenkins/agent/workspace/projectname/.dotnet/dotnet-install.sh: line 908: http_code: unbound variable

**Comment by al-cheb** [comment]
@onurvatan, This regression was added in https://github.com/dotnet/install-scripts/issues/136 and fixed https://github.com/dotnet/install-scripts/pull/137.

**Comment by bozturkMSFT** [comment]
Hi @onurvatan,
 Thank you for the issue.

 As @al-cheb mentioned, the fix is already merged #137 and waiting for deployment. ETA: 3-4 hours
 I will keep this task open for the time being to prevent further confusion on the resolution.

**Comment by bozturkMSFT** [comment]
The fix is now live. Let me know if the issue still exists.

Closing.

**Comment by onurvatan** [comment]
@bozturkMSFT @al-cheb  thank you for your responses. That bug seems fixed right now.
