### ISSUE TITLE
Failing on TravisCI

### ISSUE THREAD

**Issue by matkoch** [dotnet/install-scripts#140]
I'm invoke the install script from travis and get this:

```
dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100/dotnet-sdk-5.0.100-osx-x64.tar.gz
529/Users/travis/build/nuke-build/nuke/.tmp/dotnet-install.sh: line 908: http_code: unbound variable
```

**Comment by matkoch** [comment]
In case it matters, this my script: https://github.com/nuke-build/nuke/blob/65000352b980c18b000301b44c4685a9dd9b3257/build.sh#L5

**Comment by bozturkMSFT** [comment]
This issue was fixed in https://github.com/dotnet/install-scripts/issues/136.
Please use the newer version of the script located at https://dot.net/v1/dotnet-install.sh.

**Comment by matkoch** [comment]
Thanks, haven’t seen the issue.
