### ISSUE TITLE
On Raspbian Lite with .NET 5 installed dotnet-install.sh fails to add 3.1 SDK

### ISSUE THREAD

**Issue by IKoshelev** [dotnet/install-scripts#148]
I have Raspbian Lite, `dotnet --list-sdks` produces `5.0.102 [/opt/dotnet/sdk]`. Now i'm trying to add v3.1. I ran ` bash dotnet-install.sh -v 3.1.301`, several times, its output claims 3.1 is already installed:
```
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: .NET Core SDK version 3.1.301 is already installed.
dotnet-install: Adding to current process PATH: `/home/pi/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
```

But `dotnet --list-sdks` still only gives me 5.0 (and I checked actual /opt/dotnet/sdk folder, only 5.0 is there). Not sure, what am I missing?

**Comment by bozturkMSFT** [comment]
Hi @IKoshelev,
 Install script doesn't install the sdk into the same folder as the installers. As you can see in the logs:
```
dotnet-install: Adding to current process PATH: `/home/pi/.dotnet`. Note: This change will be visible only when sourcing script.
```
you installed 3.1 into `/home/pi/.dotnet`.

When you run `dotnet --list-sdks`, you are using the sdk installed under `/opt/dotnet/` which only contains 5.0.
If you run `./home/pi/.dotnet/dotnet --list-sdks`, then you should be able to see that 3.1 is installed.

**Comment by IKoshelev** [comment]
@bozturkMSFT I see, thank you. Can you give any advice how I should go about it? Which location should I prefer?

**Comment by IKoshelev** [comment]
@bozturkMSFT actually, I don't think this script works at all on Raspbian. I removed all existing dotnet folders, re-ran the script, got no errors, but no result either. I had to download binaries manually and install it via
```
sudo apt-get install curl libunwind8 gettext
sudo mkdir -p /opt/dotnet && sudo tar zxf ARCHIVE_NAME.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin
dotnet --version
```
As described here https://ivanderevianko.com/2019/06/install-net-core-3-0-on-raspberry-pi

**Comment by bozturkMSFT** [comment]
Can you explain what you mean by "but no result either"?

I suspect that you are having trouble accessing the dotnet executable that you just installed. The script adds the install directory to PATH, but that doesn't persist after you logout. So you have to either specify the full path to dotnet every time you want to invoke `dotnet` or add the directory to PATH in a persistent way ([this](https://www.raspberrypi.org/forums/viewtopic.php?t=9033) may help)

As an alternative method, also provided in the sample you shared, you can create a symlink:
```
sudo ln -s /home/pi/.dotnet/dotnet /usr/local/bin
```

**Comment by IKoshelev** [comment]
@bozturkMSFT You are probably right. I glimpsed that the output mentioned adding installation dir to PATH, but didn't pick up what the warning meant

```
dotnet-install: Adding to current process PATH: `/home/pi/.dotnet`. Note: This change will be visible only when sourcing script.
```

`his change will be visible only when sourcing script.` - that part is not clear me. Thank you for clarifying it.

P.S. I wonder how many people would not pick-up this warning? Maybe it could be clarified a bit?

**Comment by bozturkMSFT** [comment]
We haven't had many reports on this, but we will definitely keep an eye out.
I will close this issue for now. Feel free to comment if you are still having trouble.
