### ISSUE TITLE
spawn EACCES

### ISSUE THREAD

**Issue by naadev** [dotnet/install-scripts#149]
Issue running in Ubuntu:

Run actions/setup-dotnet@v1
  with:
    dotnet-version: 5.0.x
/home/gha-actions/actions-runner/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh --version 5.0.103
Error: There was an error when attempting to execute the process '/home/gha-actions/actions-runner/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh'. This may indicate the process failed to start. Error: spawn /home/gha-actions/actions-runner/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh EACCES

The user is gha-actions and has permissions on the full gha-actions/actions-runner after running chown -R gha-actions /home/gha-actions/actions-runner

Any clue?

**Comment by bozturkMSFT** [comment]
Hi @naadev,
 Can you check what permissions you have on the file? If you don't have `execute`, can you add it using
```
chmod +x dotnet-install.sh
```
and retry?

**Comment by naadev** [comment]
thanks for your answer Bekir...

-rwxrwxrwx 1 gha-actions runners 34939 Sep 29 15:12 /home/gha-actions/actions-runner/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh*
 
could it be related to my corporate proxy? I'm trying to setup npm right now with npm config set proxy

**Comment by bozturkMSFT** [comment]
The script prints some messages before attempting to make its first network call. So, if there was a proxy related issue, you would see some error messages related to a failed download.

Are you the owner of the file? Maybe creating a new file and copying the scripts contents into it then running it could help. I'm not familiar with this issue and I'm mostly guessing at this point.

**Comment by naadev** [comment]
I've found something weird in diagnostics... 

Depending on the host, this issue is found or not. In the host where issue can be reproduced I've seen a system access error:

![image](https://user-images.githubusercontent.com/5873034/108350947-22c94f80-71e5-11eb-9725-3152ce1d26ec.png)

Looks like there could be some kind of issue on writing/reading process information

**Comment by bozturkMSFT** [comment]
That also supports the idea that there is an issue with file system permissions. Since this isn't related to the script itself, I will go ahead and close this issue now. But feel free to comment further and let us know if you find a solution.
