### ISSUE TITLE
Hidden ~/.dotnet folder fails install script

### ISSUE THREAD

**Issue by heaths** [dotnet/install-scripts#150]
In PowerShell, if a directory or file is hidden, `Get-Item` and `Get-ChildItem` will fail by default. On Windows, I like to hide my dot directories and files to avoid all the clutter (there's more of them than non-dot entries) like on various linux shells. The fix is to pass `-Force` for hidden items.

https://github.com/dotnet/install-scripts/blob/680111c6d24788d0c931e92e0cac0e8cf5befedd/src/dotnet-install.ps1#L782

**Comment by bozturkMSFT** [comment]
Hi @heaths,
 Thank you for the issue and the PR. We will get this merged once approved.

**Comment by adegeo** [comment]
I'm opening another issue as I have a problem somewhat related to this, but I don't think you should be installing .NET into that folder. In fact, the scripts should probably prevent it. That folder is generated by .NET when it does things, such as installing global tools.
