### ISSUE TITLE
Installing a runtime older than 5.0 with the new scripts adds unnecessary errors in the error variable

### ISSUE THREAD

**Issue by nkolev92** [dotnet/install-scripts#152]
```console
> dotnet-install.ps1 -Runtime dotnet -Channel 2.2 -i cli -NoPath -ErrorVariable err

dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: .NET Core Runtime version 2.2.7 is already installed.
dotnet-install: Binaries of dotnet can be found in C:\Users\Roki2\Documents\Code\NuGet\NuGet.Client\cli\

> $LASTEXITCODE
0

> echo $err

Unable to download https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.7/productVersion.txt.
At C:\Users\Roki2\Documents\Code\NuGet\NuGet.Client\cli\dotnet-install.ps1:301 char:17
+                 throw $DownloadException
+                 ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Unable to download https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.7/productVersion.txt.
```

Note that the last part appears up to ~20 times. 

If you install 5.0.0, then you don't get these messages.

`https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.7/productVersion.txt` doesn't exist, but `https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0/productVersion.txt` does.

**Comment by bozturkMSFT** [comment]
Hi @nkolev92,
 Thank you for the issue.

 Can you help me understand the impact this is having on your team?

 We put install scripts into "maintenance mode" some time ago, which means that we are only able to fix high-impact or blocking issues as the availability of our team allows. Knowing the impact will help us better prioritize this.

 As a workaround, can you ignore the error string if `$LASTEXITCODE` is zero?

**Comment by nkolev92** [comment]
This is affecting our tests. 
NuGet is a part of the SDK, so we have a set of integration tests that run against different frameworks. To do that we need to download a version of the SDK from a specific branch and we need a couple of different runtimes. 

Currently, I am working around it by shelling out to a new process. 
We are calling the script from a script, so I wasn't sure there's a way for me to ignore the error variable.
Given that we have a workaround this is a nice to have. 

https://github.com/dotnet/install-scripts/issues/153 is one that's causing pain, this is mostly inconvenient assuming that 5.0 runtime and forward all have the same correct resources published.

**Comment by bozturkMSFT** [comment]
We are still working on #153 and it will be resolved hopefully soon. 
For the sake of install scripts being in maintenance mode and considering that this is more of a nice-to-have feature, I will close this issue now. Let me know if this becomes a high-impact/blocking issue.
