### ISSUE TITLE
Installing from an an active channel with version latest leads to sporadic failures

### ISSUE THREAD

**Issue by nkolev92** [dotnet/install-scripts#153]
On our CI we try to install the latest 5.0.2xx SDK to test against. Unfortunately this leads to sporadic failures, and does not consistently work. 

```
[15:29:06 +0]   C:\Users\Roki2\Documents\Code\NuGet\NuGet.Client\cli\dotnet-install.ps1 -Channel release/5.0.2xx -i C:\Users\Roki2\Documents\Code\NuGet\NuGet.Client\cli -Version latest -Architecture x64 -NoPath 
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where: 
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights. 
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs. 
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.  
dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201-servicing.21123.3/dotnet-sdk-5.0.201-servicing.21123.3-win-x64.zip 
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201-servicing.21123.3/dotnet-sdk-5.0.201-servicing.21123.3-win-x64.zip is not available. 
dotnet-install: Downloading legacy link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201-servicing.21123.3/dotnet-dev-win-x64.5.0.201-servicing.21123.3.zip 
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201-servicing.21123.3/dotnet-dev-win-x64.5.0.201-servicing.21123.3.zip is not available.
```

**Comment by bozturkMSFT** [comment]
Hi @rbhanda,
 Latest version file for the branch `release/5.0.2xx` is at `https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/5.0.2xx/latest.version` which contains

```
ff3eefe79ed466e2983b87ce305c1b045294219b
5.0.201-servicing.21123.3
```

Using the version number in the `latest.version` file, install script tries to access the `productVersion.txt` file at `https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201-servicing.21120.4/productVersion.txt` which doesn't exist. Can you check why productVersion file isn't there?

Also, the version number for `release/5.0.2xx` branch inside the `latest.version` file is different than what we have in installer repo [binaries table](https://github.com/dotnet/installer#installers-and-binaries). Shouldn't they both point to the same version?

**Comment by rbhanda** [comment]
hi @bozturkMSFT 5.0.2xx SDKs have not been released yet.

**Comment by bozturkMSFT** [comment]
@rbhanda We are supplying a branch name as a channel here, so we should be able to download unreleased versions. This was also working until recently, as we have tests for this in our CI which are now failing, preventing us from merging anything.

Looking at our [build pipeline](https://dev.azure.com/dnceng/public/_build?definitionId=846&_a=summary), I see that the build on February 19th succeeded, but February 24th did not.

**Comment by bozturkMSFT** [comment]
This issue is fixed now. Please comment if you are still running into this.
