### ISSUE TITLE
Installing from an an active channel with version latest is failing

### ISSUE THREAD

**Issue by erdembayar** [dotnet/install-scripts#171]
Currently my attempt to download latest sdk is failing.
Also it looks I can choose previous version instead of latest one. Where can I find list of all available previous versions?

```
.\dotnet-install.ps1 -Channel release/5.0.2xx -i C:\NuGetProj\NuGet.Client\cli -Version latest -Architecture x64 -NoPath
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.202-servicing.21167.13/dotnet-sdk-5.0.202-servicing.21167.13-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.202-servicing.21167.13/dotnet-sdk-5.0.202-servicing.21167.13-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.202-servicing.21167.13/dotnet-dev-win-x64.5.0.202-servicing.21167.13.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.202-servicing.21167.13/dotnet-dev-win-x64.5.0.202-servicing.21167.13.zip
Could not find/download: ".NET Core SDK" with version = 5.0.202-servicing.21167.13
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
At C:\NuGetProj\NuGet.Client\cli\dotnet-install.ps1:660 char:5
+     throw "Could not find/download: `"$assetName`" with version = $Sp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find/download: ".NET Core SDK" with version = 5.0.202-servicing.21167.13
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

**Comment by bozturkMSFT** [comment]
Hi @erdembayar,
 It seems to be working now. I'm not exactly sure what the issue is, but it is possible that the files for the latest version were just being published when the script was running. The channel you are using contains nightly builds which I assume is more likely to get this kind of an error. If you want stable builds, you can use channel `5.0` instead.
 There is no version list, unfortunately.

 Let me know if the issue still continues on your machine.

**Comment by erdembayar** [comment]
@bozturkMSFT 
It's still persisting. Also where can I find all available version list? So I don't have to wait this script to work, I just select one works from recent ones.

**Comment by erdembayar** [comment]
![image](https://user-images.githubusercontent.com/8766776/112538657-56ac0d80-8d6d-11eb-9955-f9cd59600998.png)

**Comment by bozturkMSFT** [comment]
Hi @erdembayar,
 I'm not aware of any version lists for nightly builds. For public ones, you can check https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json.

 The link generated by your script is different than what is generated on my machine:
```
https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.202-servicing.21167.13/dotnet-sdk-5.0.202-servicing.21167.13-win-x64.zip //Yours
https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.202-servicing.21167.13/dotnet-sdk-5.0.202-win-x64.zip // Correct one
```

Can you confirm that you are using the latest version of the script?
Can you also check if the `C:\NuGetProj\NuGet.Client\cli` contains a `global.json` file? If yes, can you share the its content?

**Comment by erdembayar** [comment]
Maybe I don't need latest version, I solved my problem another way.
