### ISSUE TITLE
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to dot.net:443 

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/install-scripts#174]
Our build basically runs:

```
$ ./dotnet-install.sh --version 5.0.201 --install-dir ~/.dotnet/ --verbose
```

Occasionally this fails with:

```
/Users/runner/.dotnet/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to dot.net:443 
##[error]Bash exited with code '35'.
```

Is it possible that `dotnet-install.sh` could add some kind of delay/retry mechanism here? It might make the script more reliable.

Full log: [177.txt](https://github.com/dotnet/install-scripts/files/6311595/177.txt)

**Comment by bozturkMSFT** [comment]
Hi @jonathanpeppers,
 I can't see any lines from install scripts in the log file you shared. Moreover, we already have retry mechanism in the scripts. Could it be that the `curl` is being called by some other script here?

**Comment by jonathanpeppers** [comment]
Ok yeah, we do this right before running the script:
```
curl -L https://dot.net/v1/dotnet-install.sh --retry 5 --retry-max-time 300 > dotnet-install.sh
```

Is there a better/recommended way to do this?

**Comment by bozturkMSFT** [comment]
Adding retry logic to that `curl` call similar to what we did here would probably help:
https://github.com/dotnet/install-scripts/blob/1110c871152440f5fe38117e05725ea1f1b2b7f3/src/dotnet-install.sh#L931

**Comment by jonathanpeppers** [comment]
Thanks, I'll give this a try.
