### ISSUE TITLE
Install 6.0preview on CentOS7

### ISSUE THREAD

**Issue by victoralvesp** [dotnet/install-scripts#175]
When trying to install a preview version using

```bash
dotnet-install.sh -c Preview -v latest
```
I get the folowing error:
curl: (22) The requested URL returned error: 404 The specified blob does not exist.

Is there a way to install dotnet 6.0preview on CentOS7 using this script?

**Comment by bozturkMSFT** [comment]
Hi @victoralvesp, 

"Preview" is not a valid channel for the scripts. You can check the available options [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#options).

  The proper way to get the latest 6.0 build (including the previews) is to use `dotnet-install.sh -Channel 6.0`. However there is currently an issue this and it doesn't work. We are working on this. I will let you know once it is fixed.

 In the meantime, you can directly use the version number to install the preview, such as:
 `dotnet-install.sh -Version 6.0.100-preview.3.21201.3

Let me know if this helps.

**Comment by bozturkMSFT** [comment]
6.0 previews are fixed now. You can use:
```
dotnet-install.sh -Channel 6.0
```
get the latest 6.0, including the previews.

**Comment by victoralvesp** [comment]
Thank you very much!
