### ISSUE TITLE
Always states "already installed"

### ISSUE THREAD

**Issue by jsreynolds** [dotnet/install-scripts#176]
Windows 10 20H2, Powershell 7.13.

Running `./dotnet-install.ps1 -Runtime aspnetcore -Channel 3.1 -Version latest -Architecture x64` as administrator

always returns that it is already installed, even though no dotnet core versions are actually installed.

I believe it's ~ line 554, function ` Is-Dotnet-Package-Installed` causing the problem. It oddly just seems to be checking for the existence of the `APP_DATA\Local\Microsoft\dotnet ` directory for example. I haven't dug in, but I consistently get this error.

**Comment by bozturkMSFT** [comment]
Hi @jsreynolds ,
 Script not only check for the existence of 'dotnet' folder, it also checks if the version that you are trying to install is the same as one of the installed versions.
 Can you check what you have under `APP_DATA\Local\Microsoft\dotnet` folder?
 Was this working for you before and got broken recently?

**Comment by jsreynolds** [comment]
I'm sorry - I wonder if I'm misunderstanding the install. Under C:\Users\foo\AppData\Local\Microsoft\dotnet\Shared` it does indeed look like there are installations of both in folders like, "Microsoft.AspNetCore.App" for example.

I was running the Powershell script as admin, hoping for a machine-wide installation like I would get if I ran it by hand as administrator.

Am I off / missing something?

**Comment by bozturkMSFT** [comment]
Install script only updates the PATH for the current shell session. If you close the powershell window, you won't be able to access `dotnet` command from a new shell window unless you type the full path like ` C:\Users\foo\AppData\Local\Microsoft\dotnet\dotnet.exe`.

You can:
- Add `C:\Users\foo\AppData\Local\Microsoft\dotnet\` to your PATH, or
- Access dotnet using full path `C:\Users\foo\AppData\Local\Microsoft\dotnet\dotnet.exe --info`

On the other hand, you can use one of the installers which will automatically update the PATH for you. Is there a reason why you chose to use install scripts and not one of the installers?

**Comment by jsreynolds** [comment]
We're looking to deploy dotnet 3.1 and 5 on servers. We have a mixture of Winforms, console, x86 and x64 - and sometimes (required by Graph) aspnetcore required. So that's sometimes 6 installations. So we're looking to deploy at the *machine* level, not per user. 

I should have read the `InstallDir` more carefully. I guess I could provide my own path - it looks like running the installers puts them all in `C:\Program Files\dotnet\shared` for example? But then that would leave the PATH variable to do too. Not sure if that's the right direction.

**Comment by bozturkMSFT** [comment]
Scripts are probably the right choice for the scenario you describe. Installers require user interaction, which would be hard to implement on large number of machines.
Like you mentioned, you can use `InstallDir` to select where the files should be placed. You can also set the machine level PATH within your script, which should allow access to the SDK from all user accounts.

**Comment by jsreynolds** [comment]
Side note. The [dotnet-core-uninstall](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows)  tool doesn't locate the stock script installs using their tool.

The dotnet core installs I did, which do indeed reside in `APP_DATA\Local\Microsoft\dotnet` do not have an uninstaller, either. 

I'm beginning to think that my best bet is to just line up the executables and run `dotnet-sdk-3.1.301-win-x64.exe /install /quiet /norestart` for example.

**Comment by bozturkMSFT** [comment]
That sounds like an option too, as long as you have admin rights to the machine. Install scripts are mostly used in CI where machine state is cleared after each run so uninstalling is not necessary.

**Comment by jsreynolds** [comment]
That makes sense. Thanks again!

Follow-up... just did a small .bat script which did the executable run like above, and it worked brilliantly. 

`
REM dotnet 3.1.x
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 3.1\aspnetcore-runtime-3.1.14-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 3.1\aspnetcore-runtime-3.1.14-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 3.1\dotnet-runtime-3.1.14-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 3.1\dotnet-runtime-3.1.14-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 3.1\windowsdesktop-runtime-3.1.14-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 3.1\windowsdesktop-runtime-3.1.14-win-x86.exe" /install /quiet /norestart
REM dotnet 5.x
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 5.0\aspnetcore-runtime-5.0.5-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 5.0\aspnetcore-runtime-5.0.5-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 5.0\dotnet-runtime-5.0.5-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 5.0\dotnet-runtime-5.0.5-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 5.0\windowsdesktop-runtime-5.0.5-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\houstons\systems\Software\Microsoft\dotNet\core 5.0\windowsdesktop-runtime-5.0.5-win-x86.exe" /install /quiet /norestart
`

**Comment by jsreynolds** [comment]
That makes sense. Thanks again!

Follow-up... just did a small .bat script which did the executable run like above, and it worked brilliantly. 

```
REM dotnet 3.1.x
START "" /WAIT "\\Software\Microsoft\dotNet\core 3.1\aspnetcore-runtime-3.1.14-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 3.1\aspnetcore-runtime-3.1.14-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 3.1\dotnet-runtime-3.1.14-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 3.1\dotnet-runtime-3.1.14-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 3.1\windowsdesktop-runtime-3.1.14-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 3.1\windowsdesktop-runtime-3.1.14-win-x86.exe" /install /quiet /norestart
REM dotnet 5.x
START "" /WAIT "\\Software\Microsoft\dotNet\core 5.0\aspnetcore-runtime-5.0.5-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 5.0\aspnetcore-runtime-5.0.5-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 5.0\dotnet-runtime-5.0.5-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 5.0\dotnet-runtime-5.0.5-win-x86.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 5.0\windowsdesktop-runtime-5.0.5-win-x64.exe" /install /quiet /norestart
START "" /WAIT "\\Software\Microsoft\dotNet\core 5.0\windowsdesktop-runtime-5.0.5-win-x86.exe" /install /quiet /norestart
```
