### ISSUE TITLE
dotnet-install.ps1 too verbose

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/install-scripts#19]
## Steps to reproduce

I see this when cloning and building dotnet/corefx.

It prints:

```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
dotnet-install: Adding to current process PATH: "F:\gh\corefx\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
```

The third line confuses me:
```
dotnet-install: Adding to current process PATH: "F:\gh\corefx\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
```

I'm not running PowerShell, and don't know about PATH. Maybe the script invoker cares, but as a user I don't. Shouldn't this message me silenced unless the caller uses a "-Verbose" or similar switch?

## Environment data
`dotnet --info` output:

**Comment by donJoseLuis** [comment]
The need tracked in this issue should be a requirement in the re-engineering effort. Moving to the re-engineering project.

**Comment by donJoseLuis** [comment]
@BruceForstall greetings.  Please let us know if this is something you still feel strongly about.

- your flow is implicitly invoking PS1 script(s)
- therefore, the message you called out as too verbose
- it appears that particular message was explicitly added to address customers concerns

The one option I could foresee is enabling some configurable verbosity level, but I would like to have good use cases to merit this.

**Comment by BruceForstall** [comment]
I don't care much anymore...
