### ISSUE TITLE
Architecture not supported

### ISSUE THREAD

**Issue by orangesqueeze** [dotnet/install-scripts#191]
When trying to install using powershell from an Ubuntu 18.04 host, I get 'architecture not supported' error - I have amd64 and PowerShell 7.1.3 installed.
This is how I'm trying:
Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
 ./dotnet-install.ps1 -InstallDir '~/.dotnet'
Output:
![image](https://user-images.githubusercontent.com/84855873/119671804-bba1e380-be42-11eb-8da4-014a2065b8c7.png)

**Comment by bekir-ozturk** [comment]
Hi @orangesqueeze,
 The script seems to be failing to detect the architecture. Can you share the logs with "-Verbose" flag specified?

 You can get around this by explicitly passing the architecture like `-Architecture x64`.

**Comment by orangesqueeze** [comment]
Thank you for the architecture parameter hint! However, now seems that the file cannot be downloaded.
 ![image](https://user-images.githubusercontent.com/84855873/119683993-d0837480-be4c-11eb-8cb0-4cc21657c6f9.png)
