### ISSUE TITLE
Document PS1 problem & fix self-help content

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/install-scripts#192]
We should document that the PS1 can fail if **erroractionpreference** is not configured for 'stop'

symptom:
- script does not install the target & exits with code 0

root cause.
- running PS1 via imported script block causes $erroractionpreference in the dotnet-install.ps1 script to not apply in some cases.
- Failure: write lock on dotnet.exe is ignored due to **erroractionpreference** not being configured for 'stop'

work around.
- set $erroractionpreference='stop' in the user's PowerShell environment before invoking the dotnet-install script

**Comment by bekir-ozturk** [comment]
Considering the low occurrence rate and the impact, this issue is unfortunately out of our availability within the maintenance mode. Please let us know if this issue has a high impact on your use case and you think it should be reopened.
