### ISSUE TITLE
Configure install scripts to support very slow network connections 

### ISSUE THREAD

**Issue by MattGal** [dotnet/install-scripts#195]
As reported by user @kant2002 on https://github.com/dotnet/arcade/issues/7458 :

> By some reasons my internet connection is relatively slow. So default timeout of 20 minutes in dotnet-install.ps1 for downloading .NET does not work for me.
> It would be nice if that timeout can be configured.
> 
> Right now timeout in that script is hardcoded like that:
>
 
> ``` 
> # Default timeout for HttpClient is 100s.  For a 50 MB download this assumes 500 KB/s average, any less will time out
> # 20 minutes allows it to work over much slower connections.
> $HttpClient.Timeout = New-TimeSpan -Minutes 20
> ```
> And since that script is downloaded, each time I do git clean -xdf my timeout modifications reset to 20 minutes.

If for some reason this change is not acceptable, we should probably publish minimum network bandwidth requirements for users somewhere so they know what to expect.

**Comment by bekir-ozturk** [comment]
Hi @kant2002,

 Thank you very much for the issue.

 The scripts have been and still are in a maintenance-only state where we are only able to respond to high-impact incidents. Unfortunately, our availability is quite limited for all other issues.

 If you could create a PR to increase the duration, I would be happy to review. But the deployment takes time and the scripts will not be immediately available at dot.net website.

**Comment by kant2002** [comment]
@bekir-ozturk I send PR where I add parameter which allow to control modification. I understand that you have have other priorities so I can wait.
