### ISSUE TITLE
Added -Verbose command line option and resulting commands failed.

### ISSUE THREAD

**Issue by mtwoodbury** [dotnet/install-scripts#201]
Adding `-Verbose` and got this `-Quality` error

```amazon-ebs: VERBOSE: dotnet-install: Get-CLIArchitecture-From-Architecture -Architecture "<auto>"
amazon-ebs: VERBOSE: dotnet-install: Get-Machine-Architecture
amazon-ebs: VERBOSE: dotnet-install: Get-CLIArchitecture-From-Architecture -Architecture "AMD64"
amazon-ebs: VERBOSE: dotnet-install: Get-NormalizedQuality -Quality "Files\dotnet"
amazon-ebs: Exception: InstallDotNet Failed for dotnet-install.ps1
  ==> amazon-ebs: InstallDotNetCore : Exception: 'Files\dotnet' is not a supported value for -Quality option. Supported values are:
  ==> amazon-ebs: daily, signed, validated, preview, ga. If you think this is a bug, report it at
  ==> amazon-ebs: https://github.com/dotnet/install-scripts/issues
```

**Comment by AR-May** [comment]
@mtwoodbury 
Could you please specify the exact command you are using?
(Remove any secrets if the command have them, of course)

Seems like either a parsing error or a problem with a command.

**Comment by mtwoodbury** [comment]
Egg on face. Should have done more testing...
Invoke-Expression "& `"$tmpFolder\$dotnetInstallScript`" -Channel $Channel -Runtime dotnet -InstallDir $dotnetRoot"
where dotnetroot is c:\program files\dotnet. I needed 
`$dotnetRoot = '"C:\Program Files\dotnet"'` so the space was ignored. Those quotes still get me.
Installing on an AWS AMI and it works very well. Thanks.
The docs say the install directory will be added to the path, and I'm banking on that. Sorry for the inconvenience.

**Comment by AR-May** [comment]
No problem, glad to hear that everything works. 
Please do not hesitate to reopen the issue or fill a new one in case you get problems.
