### ISSUE TITLE
Unrecognized options are used with wget on Alpine

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/install-scripts#216]
Options `--waitretry` and `--connect-timeout` are not available on `wget` that comes with Alpine.

Actual:
If curl is not installed on the machine, `wget` is used for downloads. Because of the unrecognized options listed above, the operation fails.

Expected:
Scripts should be able to install the SDK using wget on Alpine.

**Comment by KalleOlaviNiemitalo** [comment]
The fixed version of the script is not yet available from <https://dot.net/v1/dotnet-install.sh>, which redirects to <https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh>. Is the fix going to be deployed there?
