### ISSUE TITLE
How to spcify dotnet install dir when starting dotnet application

### ISSUE THREAD

**Issue by Archieeeeee** [dotnet/install-scripts#228]
Hello,
The dotnet is installed at “%LocalAppData%\Microsoft\dotnet” after running this script, but when I run an app it still says dotnet is not installed, it seems it tries to locate dotnet.exe in "%ProgramFiles%\dotnet" even if I set PATH to “%LocalAppData%\Microsoft\dotnet” , how to fix this, thank you

**Comment by bekir-ozturk** [comment]
Hi @Archieeeeee,
 
 If you run the script, the location of newly installed .NET will be added to the PATH _temporarily for that powershell session only_. If you close powershell and open a new one, you won't be able to access dotnet command directly.

 Manually adding the location to PATH should work. But I can't tell what might be wrong in your case without more info about the steps you followed.

Could you send the output from your terminal? That would help figure out the issue.

**Comment by bekir-ozturk** [comment]
Hey @Archieeeeee,
 We haven't heard from you in a while and I will take that as you have solved the issue. I will close this issue for the time being. Please feel free to comment if the issue still persists and I will reopen.
