### ISSUE TITLE
dotnet-install-script Use Def AzureFeed 'dotnetcli.azureedge.net/dotnet' To Slow In China

### ISSUE THREAD

**Issue by eveloki** [dotnet/install-scripts#236]
Please Add  Azure Cdn support to make sure we can acess it much more quickly,  much appreicatte ,Thanks

**Comment by bekir-ozturk** [comment]
Hey @eveloki,
 Thanks for the issue.
 CDN is already available in our storage. It is used by default unless you specify `--no-cdn` option when running the scripts.

 The only exception to this is `latest.version` files, which are not retrieved through CDN at the moment. The reason behind this is that `latest.version` files can be updated as new SDK builds are available. Having CDN delays propagating these changes to the scripts. However, this shouldn't be much of an issue as these files are very small in size (sample file [here](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/LTS/latest.version)). Moreover, we are working on a change that will allow accessing latest.version files through CDN as well.

 If you suspect that CDN is not used in some cases other than `latest.version` files, please capture the console output using `-verbose` flag and share it with us. In that case, I will reopen the issue to investigate further.
