### ISSUE TITLE
dotnet for x86 will be installed on s390x

### ISSUE THREAD

**Issue by skriesch** [dotnet/install-scripts#237]
I have got a VM with openSUSE Leap 15.3 on a mainframe in the LinuxONE Community Cloud (s390x).
The first thing I identified in this installation script is, that only old Linux distributions are listed under platforms.
I did a try with openSUSE Leap 15.3.

The installer is downloading a tar archive for x86 without any error message, that s390x would not be supported.
I know, that there is a collaboration between Microsoft and IBM, that .Net 6 should be supported for s390x now.
But the tar archive for x86 is the wrong choice by the installer.
It should be a tar archive for s390x.

If you need mainframe resources for community stuff buildings, you can ask at IBM for z/VMs in the LinuxONE OSS Community Cloud: lyz@ibm.com

**Comment by bekir-ozturk** [comment]
Hi @skriesch,
 Thank you for the issue.
 At the moment, .NET does not generate s390x specific archives. You can see the list of all the versions an the generated archives for each supported platform under the "[Installers and Binaries](https://github.com/dotnet/installer#installers-and-binaries)" section in dotnet/installer repo.
 If you think that there should be binaries generated separately for s390, please create a new issue in [dotnet/installer](https://www.github.com/dotnet/installer) repo.
 I will close this one for the time being. Let me know if you think it should be reopened.

**Comment by skriesch** [comment]
There is continuously a bug in the script.
Nothing should be downloaded or installed, if the architecture is not supported.
There should happen an error message for unsupported architectures then.

**Comment by bekir-ozturk** [comment]
Hey @skriesch,
 I agree that there should be an error on unsupported architectures. To help me investigate this better, could you run the following command on your machine and share the output with me?
```
uname -m
```

**Comment by skriesch** [comment]
linux1@opensusesarah:~> uname -m
s390x
