### ISSUE TITLE
DownloadFile and Extract-Dotnet-Package are really slow

### ISSUE THREAD

**Issue by jetersen** [dotnet/install-scripts#245]
`DownloadFile` and `Extract-Dotnet-Package` functions are 3x slower than compared to WebClient and 7zip on the same hosted VMs on GitHub actions.

Reported on 
https://github.com/actions/virtual-environments/issues/3577
https://github.com/actions/setup-dotnet/issues/260

**Comment by IvanZosimov** [comment]
Hi, @bekir-ozturk 👋 Are there any updates on this issue?

**Comment by YuliiaKovalova** [comment]
Hi @IvanZosimov ,

No updates here, development hasn't been undergoing. 
I will inform you if we start working on it.

**Comment by baronfel** [comment]
There's been a lot of internal investigations, and we're in contact with the github actions teams about runner-configurations that might make particular aspects of our scripts faster. Those teams have action items and in any case there's nothing actionable on our end here (i.e. we're not going to change to a non-build-in zip tool that would add a prerequisite to all users of the scripts, etc.). As a result, I'm going to close this.
