### ISSUE TITLE
dotnet-install script causes shell to exit

### ISSUE THREAD

**Issue by JohnRusk** [dotnet/install-scripts#25]
## Steps to reproduce

1. Create an Ubuntu 16.04 VM in Azure
1. Run the following:
  * `wget https://dot.net/v1/dotnet-install.sh`
  * `chmod 700 dotnet-install.sh`
  * `source dotnet-install.sh --shared-runtime --version 1.1.2`

## Expected  behavior

A message is displayed about missing dependencies (libuwind8 etc)

## Actual behavior

It just exits my shell. Unless its a subshell, this results in my whole terminal window just closing.

## Workaround

Install all the dependencies first, with `sudo apt-get install curl libunwind8 gettext apt-transport-https`

**Comment by donJoseLuis** [comment]
@JohnRusk greetings.  The side effect issue you mentioned is tracked in #36 

Problem summary:
- when the scripts (either PS1 or SH) run into trouble the container is killed

**Comment by vlada-shubina** [comment]
We agreed not to fix the error handling when sourcing dotnet-install.sh script at the moment as it requires a lot of efforts for changing the error handling.  As the workaround, the script can be launched in the subshell.
