### ISSUE TITLE
Script fails on Windows Server 2012 with error "Property 'DontShow' cannot be found"

### ISSUE THREAD

**Issue by cailyoung** [dotnet/install-scripts#250]
Hi there,

Our image builds for Windows Server 2012 have started failing with this error:

```
Property 'DontShow' cannot be found for type
'System.Management.Automation.ParameterAttribute'.
At C:\Users\Administrator\AppData\Local\Temp\install-dotnet\dotnet-install.ps1:
106 char:4
```

I believe (although it's a very old version) that Server 2012 (non-R2) is still [supported](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#dependencies) for .NET Core installs.

Our VMs are running PowerShell 3.0, to my knowledge.

Looks like the change in #233 added this.

**Comment by YuliiaKovalova** [comment]
Hello,

Thank you for reaching us and providing detailed information. Our team is working on the investigation of this issue. 
I will return to you since I have more details.

**Comment by YuliiaKovalova** [comment]
Hello,

We have investigated the issue, and you are right - it is related to the mentioned pull request. The problem is that Power Shell 3.0 doesn't support "Dont show" attribute. 
As a quick solution, we recommend upgrading the current version at least to 4.0.

**Comment by cailyoung** [comment]
> we recommend upgrading the current version at least to 4.0
I recognise that's a good workaround, however our VMs are test environments to replicate older customers who haven't (or won't) do that upgrade.

**Comment by YuliiaKovalova** [comment]
Hi @cailyoung,

We have fixed this issue. The provided solution doesn't require Power Shell version updates, so you can return to your previous experience once the fix is deployed. It is planned to be done within a week.
