### ISSUE TITLE
Specifying valid SKD versions result on: Failed to resolve the exact version number.

### ISSUE THREAD

**Issue by Jeiesel-PlainConcepts** [dotnet/install-scripts#253]
I am trying to automate the installation of .NET SDK v6.0.1XX quality GA

Running one-liner give in [dotnet-install-scrip examples](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#examples) weeks ago worked properly but now it fails specifying correct value versions saying: Failed to resolve the exact version number.

Powershell command I run is the following with it result: 
PS > powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointMan 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 6.0.1XX -Quality GA"       
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visi

At line:1162 char:5
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to resol...version number.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to resolve the exact version number.

**Comment by bekir-ozturk** [comment]
Hi @Jeiesel-PlainConcepts,
 The following command works correctly on my machine. 
```
 &powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 6.0.1xx -Quality GA"
```
It may have been a temporary issue with the storages. Can you try again to see if it works?

**Comment by Jeiesel-PlainConcepts** [comment]
Now it is working, it should be because of what you meant about an storage temporary issue, thanks
