### ISSUE TITLE
-Channel 6.0.1xx -Quality daily fails

### ISSUE THREAD

**Issue by danmoseley** [dotnet/install-scripts#258]
```
danmoseL:~/git/performance# uname -a
Linux danmoseL 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 Linux
danmoseL:~/git/performance# cat /etc/os-release | grep PRETTY
PRETTY_NAME="Alpine Linux v3.13"
danmoseL:~/git/performance# /root/git/performance/tools/dotnet/x64/dotnet-install.sh -InstallDir /root/git/performance/tools/dotnet/x64 -Architecture x64 -Channel 6.0.1xx -Quality daily
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet_install: Error: Failed to locate the latest version in the channel '6.0.1xx' with 'daily' quality for 'dotnet-sdk', os: 'linux-musl', architecture: 'x64'.
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support.
danmoseL:~/git/performance#
```

Any pointers? (fyi @adamsitnik @jeffhandley )

**Comment by danmoseley** [comment]
Ah - perhaps it's not meaningful to request `-Quality daily` on the servicing channel?

**Comment by YuliiaKovalova** [comment]
Hello @danmoseley,

Thank you for reaching us.
Our team is working on the investigation of this issue. I will return to you since I have more details.

**Comment by YuliiaKovalova** [comment]
Hello @danmoseley,

This issue was redirected to a different team.
You can track the issue progress here: [Missing package for Alpine causing error in install-scripts repo](https://github.com/dotnet/core-eng/issues/15740)

**Comment by danmoseley** [comment]
Thanks @YuliiaKovalova

**Comment by YuliiaKovalova** [comment]
Hi @danmoseley,

I have tried to run this command after applying the fixes from the issue [script does not work on Alpine due to failed fallback for unrecognized options ](https://github.com/dotnet/install-scripts/issues/259) and it works as expected.
I suppose we can close it as a duplication of the mentioned before.
Do you have any objections?

**Comment by danmoseley** [comment]
Sure
