### ISSUE TITLE
Can install script be an single exe?

### ISSUE THREAD

**Issue by wli3** [dotnet/install-scripts#26]
Just an idea. Now we have the single and trimmed exe in 3.0. We could rewrite the install script to C# and publish it as win32, mac and Linux generic self contained binaries.

C# is easier to maintain than 2 scripting language. And it can also reduce the platform dependency.

**Comment by donJoseLuis** [comment]
We are tracking re-engineering the scripts in the road map for the scripts, though at the moment we have not yet decided on the solution.
