### ISSUE TITLE
dotnet-install attempts to download non-existing blob

### ISSUE THREAD

**Issue by jasper-d** [dotnet/install-scripts#262]
When running dotnet-install.sh with `--channel 5.0`, the install script attempts to download a version that does not exist on the server (5.0.15). Workaround is to specify a version triplet (i.e. `--version 5.0.14` instead of `--channel 5.0`).

dotnet-install output:
```
$ curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 5.0 --runtime aspnetcore --install-dir /usr/share/dotnet/
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.15/aspnetcore-runtime-5.0.15-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at aka.ms link 'https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.15/aspnetcore-runtime-5.0.15-linux-x64.tar.gz' is not available.
dotnet_install: Error: Could not find `ASP.NET Core Runtime` with version = 5.0.15
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

**Comment by YuliiaKovalova** [comment]
Hi @jasper-d, 

Could you run this command again but with ` --verbose `parameter and provide a full log?
I have just tested this command on my machine and everything works as expected with the same aka.ms link: `https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.15/aspnetcore-runtime-5.0.15-linux-x64.tar.gz`.

**Comment by jasper-d** [comment]
Hi  @YuliiaKovalova, it is now working again. I assume it wasn't really an issue with the install script but rather that the metadata it got from https://dotnetcli.azureedge.net/ was updated before the updates were released yesterday.
