### ISSUE TITLE
Empty reply from https://dot.net/v1/dotnet-install.sh

### ISSUE THREAD

**Issue by dave-yotta** [dotnet/install-scripts#272]
```
> [base  5/19] RUN curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh:
#16 24.57 curl: (52) Empty reply from server
------
error: failed to solve: executor failed running [/bin/sh -c curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh]: exit code: 52
```

This has started to happen sporadically - looks like (might be) network issue over there, can you pass this on to whoever looks after dot.net?  We've seen/raised similar issues in the past.

These requests are originating from azure devops.

**Comment by YuliiaKovalova** [comment]
Hi @mairaw,

Could you take a look or redirect it to a proper person?

**Comment by dave-yotta** [comment]
Just to be clear, It's sporadic - working sometimes - just noticed it starting to fail a few times.  It might be a network issue on azure devops, but just in case it's not....

**Comment by mairaw** [comment]
@ChrisSfanos have we ever identified the root cause on this? We've seen this issue before.

**Comment by ChrisSfanos** [comment]
No - it's always been sporadic and folks have poked around but nothing was ever conclusive

**Comment by YuliiaKovalova** [comment]
Hi @mairaw ,

Do you have any updates on it? Is any work required from install-scripts side?
