### ISSUE TITLE
dotnet-install.ps1 when ran on windows-arm64 installs x64 version if --architecture is not specified

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/install-scripts#283]
There is an issue in the script in getting the architecture. When I run this script on windows-arm64 machine with powershell (running on x64), the PROCESSOR_ARCHITECTURE value returned is AMD64 and it falsely installs x64 version. Is there a robust way to know what is the architecture of current machine?

**Comment by YuliiaKovalova** [comment]
Hi @kunalspathak,

Thank you for providing the details.
I will investigate it and return to you with updates.
