### ISSUE TITLE
dotnet-install.sh no longer working with both --version and --quality specified

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/install-scripts#285]
### Description

Our bootstrapper script for PowerShell 7 has been specifying both the version and quality and has been working until a few days ago when it started returning an error.  If I modify our script to pass just the --version and leave out --quality it works.  This is a breaking change and the error message seems to indicate this is a bug and not intended behavior.  Note that the .ps1 doesn't have this problem.

### Reproduction Steps

./dotnet-install.sh -v 7.0.100-preview.5.22307.18 -q daily -skipnonversionedfiles

### Expected behavior

dotnet should install the version specified

### Actual behavior

dotnet_install: Error: Either Quality or Version option has to be specified. See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#options for details.

### Regression?

Yes, starting failing this week

### Known Workarounds

Remove --quality and only specify --version.  The PowerShell script dotnet-install.ps1 doesn't have this problem where we continue to specify both version and quality.

### Configuration

7.0.100-preview.5.22307.18

**Comment by SteveL-MSFT** [comment]
This PR appears to have introduced a change that is causing the regression https://github.com/dotnet/install-scripts/pull/278/files

**Comment by SteveL-MSFT** [comment]
Here's the relevant section:

```sh
    if [[ "$normalized_version" != "latest" ]] && [ -n "$normalized_quality" ]; then
        say_err "Either Quality or Version option has to be specified. See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#options for details."
        return 1
    fi
```

Based on the error message, the check is that either --version or --quality has to be specified.  So it seems that this should be:

```sh
    if [[ -n "$normalized_version" ]] && [ -n "$normalized_quality" ]; then
        say_err "Either Quality or Version option has to be specified. See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#options for details."
        return 1
    fi
```

**Comment by bekir-ozturk** [comment]
@dagood has pretty much nailed it (thank you!). I have created an issue so that we can revert the latest change: https://github.com/dotnet/install-scripts/issues/287.

The bottom line is, if you specified both `--quality` and `--version`, the quality used to be ignored. Which meant that you may not have been getting the quality you asked for. With the recent update, you get an error instead which will hopefully help you write the right command that will give you the build you want.

If you want to keep the old behavior, please simply omit `--quality`.

**Comment by YuliiaKovalova** [comment]
Hi @SteveL-MSFT,

As you can see from the description above, existing behavior is valid.
But we do agree, that message is misleading so it is changed [PR: 288](https://github.com/dotnet/install-scripts/pull/288).
I expect to have it deployed tomorrow.

Sorry for delay.
