### ISSUE TITLE
dotnet-install.ps1 failing because of CIM dependency

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/install-scripts#298]
#284 introduced a call to `Get-CimInstance`, which is likely the root cause of http and ssl stress pipelines failing in dotnet/runtime (https://github.com/dotnet/runtime/issues/73154):

https://dev.azure.com/dnceng/public/_build/results?buildId=1914390&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=abae1f68-3c73-5bff-491f-f2b908580ce6&l=5555

```
Get-CimInstance: C:\dotnet-install.ps1:208
Line |
 208 |      if( ((Get-CimInstance -ClassName CIM_OperatingSystem).OSArchitect …
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | FAILED
```

These pipelines are using the `1es-windows-2022` Helix image which is equivalent of the [GitHub "hosted windows-2022 image"](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md) according to https://github.com/dotnet/runtime/issues/72096#issuecomment-1185617467. I may be wrong but I assume CIM is not available on those images.

To make the script more robust, I would consider avoiding CIM, or returning a value from `Get-Machine-Architecture` even if the CIM query is failing.

**Comment by adiaaida** [comment]
This is probably related: https://github.com/PowerShell/PowerShell/issues/11009

The failing build in question is running on a NanoServer docker image, and from the sound of it, Get-CimInstance doesn't work on nano server

**Comment by YuliiaKovalova** [comment]
Hi @adiaaida ,

Thank you for the reference.
We will substitute call to CIM dependency

**Comment by YuliiaKovalova** [comment]
Hi @antonfirsov ,

Could you help me to run your pipeline against our changes?
https://github.com/dotnet/runtime/pull/73225

**Comment by antonfirsov** [comment]
This is fixed now, thanks @YuliiaKovalova!
