### ISSUE TITLE
Scripts deadlock during resource downloading (sometimes)

### ISSUE THREAD

**Issue by bozturkMSFT** [dotnet/install-scripts#3]
On issue dotnet/sdk#11621, @Gnbrkm41 wrote:

>  It appears that the script sometimes get stuck downloading nothing (checked through taskmgr), and won't respond to Ctrl+C if I try to cancel the process during the download. The script simply gets stuck after logging dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.5.20251.2/dotnet-sdk-5.0.100-preview.5.20251.2-win-x64.zip and it takes hours for that to fail and return control.

which seems to be happening when internet is slow.

**Comment by donJoseLuis** [comment]
@bozturkMSFT , We need to determine the extent of the issue.  It must not be a high % repro, as we would have received an escalation by now.

**Comment by donJoseLuis** [comment]
@Gnbrkm41 greetings.  Just a heads up, this issue tracks the "scripts get stuck" issue you described in #4

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks
