### ISSUE TITLE
Repo for dotnet-preview-installer script

### ISSUE THREAD

**Issue by N0D4N** [dotnet/install-scripts#303]
In [.NET 7 installation instructions for Linux](https://github.com/dotnet/core/blob/main/release-notes/7.0/install-linux.md) there is link to dotnet-preview-installer script https://aka.ms/install-dotnet-preview
I would like to know in which repo is this script's source hosted at, i couldn't find it here or in [dotnet/installer](https://github.com/dotnet/installer/).
I'm sorry if this isn't correct repo to ask.

**Comment by YuliiaKovalova** [comment]
Hi @N0D4N ,

If I am not mistaken https://github.com/dotnet/sdk repo is responsible for it.

@mairaw , could you advise?

**Comment by YuliiaKovalova** [comment]
Hi @leecow,

Could you help me to find an owner of dotnet-preview-installer script?
Previously, the issue was opened against sdk repo https://github.com/dotnet/sdk/issues/11185.

**Comment by leecow** [comment]
At the moment, the script is not hosted in the open. This is probably a mistake that we can remedy. @rbhanda let's start a discussion to determine the best place for this.

**Comment by YuliiaKovalova** [comment]
Hi @N0D4N ,

The preview script has finally landed in install-scripts repo.
