### ISSUE TITLE
Failed to verify the version of installed `ASP.NET Core Runtime`.

### ISSUE THREAD

**Issue by jdarundell** [dotnet/install-scripts#307]
/util/Scratch/dotnet-install.sh --version "3.1.0" --install-dir "/usr/lib/dotnet" --architecture "arm64" --os "linux" --runtime "aspnetcore" --verbose

dotnet_install: Error: Failed to verify the version of installed `ASP.NET Core Runtime`.
Installation source: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/3.1.0/aspnetcore-runtime-3.1.0-linux-arm64.tar.gz.
Installation location: /usr/lib/dotnet.
Report the bug at https://github.com/dotnet/install-scripts/issues.
dotnet_install: Error: `ASP.NET Core Runtime` with version = 3.1.0 failed to install with an error.

Raspberry Pi 4 running Ubuntu Linux 22.04.1

dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.NETCore.App]

thank you

**Comment by YuliiaKovalova** [comment]
Hi @jdarundell ,

Could you provide a full verbose output log?

**Comment by YuliiaKovalova** [comment]
Great!
I close the ticket.
