### ISSUE TITLE
dotnet-install.sh can't parse global.json containing CRLF

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/install-scripts#308]
The `.sh` script will fail with if the `global.json` contains CRLF line endings.
```
Error: Unable to find the SDK:version node in `global.json`
```

Can the [json parsing function](https://github.com/dotnet/install-scripts/blob/6b1cc69894fa87684dbd65548f7679eed1a979e8/src/dotnet-install.sh#L517-L553) be updated to support this?

Currently this requires an ugly workaround of manually changing line endings, e.g.
```bash
sed 's/\r$//' global.json > global-lf.json
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --jsonfile global-lf.json
```

**Comment by YuliiaKovalova** [comment]
Hi @MihaZupan,

Thank you for the ticket. We are working on resolving this issue.

**Comment by YuliiaKovalova** [comment]
Hi @MihaZupan ,

It was fixed. I am planning to deploy it next week.

**Comment by MihaZupan** [comment]
Thanks Yuliia
