### ISSUE TITLE
dotnet-install.ps1 doesn't have a flag to stop dotnet.exe before updating

### ISSUE THREAD

**Issue by abatishchev** [dotnet/install-scripts#31]
I'm running the script on a server (Azure Service Fabric cluster + VMSS) while production services are running) but getting an error:

>The process cannot access the file 'C:\Program Files\dotnet\dotnet.exe' because it is being used by another process.

I wish there were a flag like `-Force` or -`Stop` that would stop all `dotnet.exe` before updating it. However [the doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) doesn't say there is one:

```
dotnet-install.ps1 [-Architecture <ARCHITECTURE>] [-AzureFeed]
    [-Channel <CHANNEL>] [-DryRun] [-FeedCredential]
    [-InstallDir <DIRECTORY>] [-JSonFile <JSONFILE>]
    [-NoCdn] [-NoPath] [-ProxyAddress]
    [-ProxyUseDefaultCredentials] [-Runtime <RUNTIME>]
    [-SkipNonVersionedFiles] [-UncachedFeed] [-Verbose]
    [-Version <VERSION>]
```

**Comment by donJoseLuis** [comment]
@marcpopMSFT where do you think this use case's fix belong? 
The scripts currently only...
1. compute the URI for the targeted resource to download
1. perform the download
1. unpack & install the bits

We discussed this in triage & concluded the script should not expand its' capabilities to stop dotnet.exe.

**Comment by donJoseLuis** [comment]
@abatishchev greetings.  Thanks for your issue.  
- Hesitation in add switches to the scripts, as these result in more code paths in an already logic-busy codebase.  
- Instead we are targeting logic simplification & resiliency improvements 

Do you think whatever triggers the install scripts in your situation could take the responsibility to check & stop dotnet.exe?

**Comment by abatishchev** [comment]
Hi @donJoseLuis,
I clearly understand the hesitation to add more stuff to the script.

For me it's getting executed by the CustomScriptExtension (CSE) extension for VMSS. It supports a URL to a script or inline. The latter is super painful to write as it's in JSON of ARM template and requires escaping too many characters. And the former is how I use it right now with the .NET script, I can just pass additional parameters, if any.

Few top issues of not having this parameter in the script itself:

- The logic to kill all dotnet processes are heavier than just one line. You need to "shield" the installation path and prevent dotnet from being restarted during installation.
- If I do that manually, it basically defeats the purpose of using the script
- If I do that manually, before running the script, then I'll have to prevent dotnet from being restarted for too long: for the time while it's being downloaded, not just installed.

Overall we're coming to an issue not with .NET but with Azure VMSS where there is no easy way to get an OS image with the latest version which also would be complaint according to the internal requirements (think TLS 1.2).

Let me throw in few mode ideas:
- Add the said flag (or the self-installation mechanism in general) to dotnet.exe itself
- Create a dedicated global tool (if that would work, I'm not too familiar with the capabilities of this mechanism)

**Comment by donJoseLuis** [comment]
@abatishchev it's fun for me to work & talk to people like you, who are passionate about software; thanks for the great reply.  

Give me a little time to discuss things internally.  I would need to find out what the north-stars are for the components relevant to the ideas you offered & assess their feasibility.  At this moment, I can't promise an outcome that will address all of your pain-points.  I will ping back on this issue in about a week.

**Comment by donJoseLuis** [comment]
Waiting on decision in relevant mail thread.  Ready to implement what's asked if it's determined the request fits the scripts' north star.

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks
