### ISSUE TITLE
dotnet-install.sh should install an x64 version of dotnet on OSX arm64 for any pre-6.0 versions

### ISSUE THREAD

**Issue by adiaaida** [dotnet/install-scripts#313]
Before 6.0, we did not have support for arm64 OSX. However, there are cases where someone may want to run dotnet of a previous version on an arm64 Mac. With Rosetta, they can run an x64 version, so that is what we should install. Or, we should error without attempting to download to inform the user that arm64 osx does not exist on that version.

**Comment by YuliiaKovalova** [comment]
Hi @adiaaida,

I am working on it.

**Comment by YuliiaKovalova** [comment]
Hi @adiaaida ,

It was fixed. I am planning to deploy it next week (Probably on Monday (05.09).
