### ISSUE TITLE
Cannot install 1.0.5 & 1.1.2 runtimes

### ISSUE THREAD

**Issue by weltkante** [dotnet/install-scripts#32]
How do you build this? I've created a new Ubuntu 18.04 VM (which can successfully build the dotnet/runtime repo) and tried running `build.sh` as outlined in the repo docs, however it immediately fails:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.5/dotnet-runtime-1.0.5-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.5/dotnet-runtime-1.0.5-linux-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.5/dotnet-ubuntu.18.04-x64.1.0.5.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.5/dotnet-ubuntu.18.04-x64.1.0.5.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core Runtime` with version = 1.0.5
```

**Comment by mfkl** [comment]
Try this workaround https://github.com/mfkl/sdk/commit/766e9472f9a445a53269e33f2e746925727cbecf @weltkante

**Comment by weltkante** [comment]
@mfkl thanks I'll have a look

Also, why was this issue moved?

@marcpopMSFT  Is the https://github.com/dotnet/sdk repo being dissolved? I was trying to build dotnet/sdk so moving the issue for building that repo to another repo seems inappropriate?

**Comment by donJoseLuis** [comment]
@weltkante greetings.  The URIs created by the script run indeed map to inexistent resources.

**Comment by marcpopMSFT** [comment]
@weltkante There were enough dotnet-install script specific issues that they were moved into this separate repo to help manage and track.

**Comment by weltkante** [comment]
@marcpopMSFT I see, thats a bit unusal, normally you'd create an external issue and refer to that, so that other people encountering the problem can still find the existing issue in dotnet/sdk instead of creating one of their own. Got me a bit confused but I guess its ok to leave things as they are now.

**Comment by bozturkMSFT** [comment]
For ubuntu, we only have the following artifacts in blob storage:
- dotnet-ubuntu-x64.1.0.5.tar.gz
- dotnet-ubuntu.16.04-x64.1.0.5.tar.gz

But the script is attempting to download for ubuntu 18.04, which doesn't exist:
- dotnet-ubuntu.18.04-x64.1.0.5.tar.gz

Maybe we can check if versionless file is good enough. If yes, we can fall back to that if an artifact specific to that OS version is not found.

**Comment by vlada-shubina** [comment]
@weltkante @marcpopMSFT this [PR](https://github.com/dotnet/sdk/pull/14094) should have fixed this issue.
Please feel free to reopen if it's still reproduced.
