### ISSUE TITLE
Adding support for Hosting Bundle

### ISSUE THREAD

**Issue by zulander1** [dotnet/install-scripts#335]
Hi,

I don't see any Hosting Bundle option or to allow multiple Runtime, is there a way to do that or we need to run two scripts:

- dotnet-install.ps1 -Channel 7.0 -Runtime dotnet
- dotnet-install.ps1 -Channel 7.0 -Runtime aspnetcore

Thank's

**Comment by MichalPavlik** [comment]
Hello, this script is meant to be used in CI environment. Is your request related to CI, or do you want to install multiple runtimes for dev machine? If it's for dev machine, we recommend to use standard installer.

**Comment by zulander1** [comment]
👍 Okay thank you
