### ISSUE TITLE
Please support installing .NET from folder

### ISSUE THREAD

**Issue by kant2002** [dotnet/install-scripts#336]
I made attempts to bring up .NET SDK build on the Loongarch and from my experience I would like to be able finally customize dotnet/runtime build to some other non MS locations (at least temporarily). In addition to changes in the dotnet/runtime which I would be discussing in that repo, I think I need change in this script.

What I am thinking would be good to have in these scripts (Linux only at least)
- Ability to install .NET SDK from file, or from folder.
- Maybe install .NET SDK from custom Nuget feed (not sure that I want to go that route, but maybe that's easier to get your buy-in)

/cc @shushanhf

**Comment by MichalPavlik** [comment]
Hello Andrii. We are sorry, but we don't support installation from unofficial sources. This script is for CI environment. The .NET installation itself is very easy. You need to just copy/extract files to some directory and set environment variable.
