### ISSUE TITLE
Not able to install .NET 6 on Service fabric VMSS 

### ISSUE THREAD

**Issue by guruvonline** [dotnet/install-scripts#343]
HI,
I executed the dotnet install with appropriate parameters as custom script extension for VMSS (for Service fabric). Script execution was success but still when I log in to VM and run dotnet.exe, it says no command found.

Do i have to set the 2 environment variables, so that i can run my .NET 6 application on VM?

Thanks

**Comment by MichalPavlik** [comment]
Hello, the script sets env. variable for the current console session. If you want to make it persistent, you must create env. variable with the path manually. Install script is intended for CI machines. For other scenarios, the standard installer is recommended way how to deploy .NET SDK on the machine.

**Comment by MichalPavlik** [comment]
Closing the issue. Feel free to reopen if you have more questions.
