### ISSUE TITLE
dotnet-install --runtime error 

### ISSUE THREAD

**Issue by Ar-mane** [dotnet/install-scripts#355]
![image](https://user-images.githubusercontent.com/46249965/222716902-b743cf91-0544-4a63-a3ff-e93ac4bd623d.png)

**Comment by YuliiaKovalova** [comment]
Hi @Ar-mane,

You need to specify the runtime for downloading, e.g. 
![image](https://user-images.githubusercontent.com/95473390/222723789-0d56e1a3-92e8-4955-8669-bdde1b4ca3a8.png)
 
Please use [documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#:~:text=the%205.0%20release.-,%2DRuntime%7C%2D%2Druntime%20%3CRUNTIME%3E,-Installs%20just%20the) for getting more details.
