### ISSUE TITLE
Using -Channel 7.0 option leads to wrong .NET SDK version installed

### ISSUE THREAD

**Issue by IvanZosimov** [dotnet/install-scripts#357]
**Description:**
Currently, the latest .NET SDK release on the channel `7.0` is [7.0.201](https://dotnetcli.azureedge.net/dotnet/release-metadata/releases-index.json). Somehow, during execution of install-scripts with the `-Channel/--channel` option set to `7.0`, .NET SDK 7.0.200 is installed. As I can see in the logs, the request to constructed by install-script URL https://aka.ms/dotnet/7.0/dotnet-sdk-win-x64.zip redirects to the wrong URL https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip with .NET SDK 7.0.200, which is wrong.

<details>
  <summary>Logs for Windows:</summary>
  <code>PS C:\Users\v\Desktop\dotnet\setup-dotnet> ./externals/install-dotnet.ps1 -Channel 7.0 -Verbose
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
VERBOSE: dotnet-install: Get-CLIArchitecture-From-Architecture -Architecture "<auto>"
VERBOSE: dotnet-install: Get-Machine-Architecture 
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = CIM_OperatingSystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: dotnet-install: Get-NormalizedQuality -Quality ""
VERBOSE: dotnet-install: Normalized quality: ''
VERBOSE: dotnet-install: Get-NormalizedChannel -Channel "7.0"
VERBOSE: dotnet-install: Normalized channel: '7.0'
VERBOSE: dotnet-install: Get-NormalizedProduct -Runtime ""
VERBOSE: dotnet-install: Normalized product: 'dotnet-sdk'
VERBOSE: dotnet-install: Resolve-Installation-Path -InstallDir "<auto>"
VERBOSE: dotnet-install: Get-User-Share-Path 
VERBOSE: dotnet-install: InstallRoot: C:\Users\v\AppData\Local\Microsoft\dotnet
VERBOSE: dotnet-install: Get-AkaMSDownloadLink -Channel "7.0" -Quality "" -Internal "False" -Product "dotnet-sdk" -Architecture "x64"
VERBOSE: dotnet-install: Retrieving primary payload URL from aka.ms link for channel: '7.0', quality: '' product: 'dotnet-sdk', os: 'win', architecture: 'x64'.
VERBOSE: dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/7.0/dotnet-sdk-win-x64.zip'.
VERBOSE: dotnet-install: Received response:
StatusCode: 301, ReasonPhrase: 'Moved Permanently', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Kestrel
  Location: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip
  Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974
  X-Response-Cache-Status: True
  Cache-Control: max-age=0, no-cache, no-store
  Pragma: no-cache
  Date: Thu, 09 Mar 2023 09:14:44 GMT
  Connection: keep-alive
  Strict-Transport-Security: max-age=31536000 ; includeSubDomains
  Content-Length: 0
  Expires: Thu, 09 Mar 2023 09:14:44 GMT
}
VERBOSE: dotnet-install: The redirect location retrieved: 'https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip'.
VERBOSE: dotnet-install: Received response:
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Accept-Ranges: bytes
  Age: 84713
  Date: Thu, 09 Mar 2023 09:14:44 GMT
  ETag: 0x8DB0E8D7A5697F5
  Server: ECAcc (frc/4CC0)
  X-Cache: HIT
  x-ms-blob-type: BlockBlob
  x-ms-lease-status: unlocked
  x-ms-request-id: 6e218ab7-701e-0009-48a2-5122e7000000
  x-ms-version: 2009-09-19
  Content-MD5: ydyWoOiB7+uPZk8GtJP/qg==
  Content-Type: application/octet-stream
  Last-Modified: Tue, 14 Feb 2023 13:15:00 GMT
  Content-Length: 265427093
}
VERBOSE: dotnet-install: Retrieved primary named payload URL from aka.ms link: 'https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip'.
VERBOSE: dotnet-install: Downloading using legacy url will not be attempted.
VERBOSE: dotnet-install: Version: '7.0.200'.
VERBOSE: dotnet-install: Get-Product-Version -SpecificVersion "7.0.200" -PackageDownloadLink "https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip"
VERBOSE: dotnet-install: Get-Product-Version-Url -Flattened "True" -AzureFeed "" -SpecificVersion "7.0.200" -PackageDownloadLink "https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip"
VERBOSE: dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/sdk-productVersion.txt
VERBOSE: dotnet-install: Get-Product-Version-Url -Flattened "False" -AzureFeed "" -SpecificVersion "7.0.200" -PackageDownloadLink "https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip"
VERBOSE: dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/productVersion.txt
VERBOSE: dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/sdk-productVersion.txt
VERBOSE: dotnet-install: Product version: '7.0.200'.
VERBOSE: dotnet-install: Generated aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.200/dotnet-sdk-7.0.200-win-x64.zip with version 7.0.200
VERBOSE: dotnet-install: Checking if the version 7.0.200 is already installed
VERBOSE: dotnet-install: Is-Dotnet-Package-Installed -InstallRoot "C:\Users\v\AppData\Local\Microsoft\dotnet" -RelativePathToPackage "sdk" -SpecificVersion "7.0.200"
VERBOSE: dotnet-install: Is-Dotnet-Package-Installed: DotnetPackagePath=C:\Users\v\AppData\Local\Microsoft\dotnet\sdk\7.0.200
dotnet-install: .NET Core SDK with version '7.0.200' is already installed.
VERBOSE: dotnet-install: Current process PATH already contains "C:\Users\v\AppData\Local\Microsoft\dotnet\"
</code>
</details>

If this bug can't be fixed by your team, may I ask you to redirect it to the team responsible for the https://aka.ms/dotnet API? This issue breaks our customers' workflows.

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Expected behavior:**
.NET SDK 7.0.201 is installed

**Actual behavior:**
.NET SDK 7.0.200 is installed

**Comment by Romfos** [comment]
please, fix it asap

**Comment by MichalPavlik** [comment]
Hello, I'm sorry you experience this issue. We contacted our partners to resolve this problem.

**Comment by MichalPavlik** [comment]
Could you please try it now? It's fixed and I was able to install 7.0.201 with 7.0.2xx channel.

**Comment by Romfos** [comment]
it works for me. thank you
