### ISSUE TITLE
Error regarding installation of .NET 7.0 Acquisition Failed: Cannot set property

### ISSUE THREAD

**Issue by ip240Z** [dotnet/install-scripts#376]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Cannot set property. Property setting is supported only on core types in this language mode.
At line:1 char:5
+ & { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointMa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage
 
C:\Users\***\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.6.0\dist\install 
scripts\dotnet-install.ps1 : Cannot invoke method. Method invocation is supported only on core types in this language 
mode.
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\***\.vscode\extensions\ms-dotnettool ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [dotnet-install.ps1], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage,dotnet-install.ps1
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Cannot set property. Property setting is supported only on core types in this language mode.
At line:1 char:5
+ & { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointMa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage
 
C:\Users\\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.6.0\dist\install 
scripts\dotnet-install.ps1 : Cannot invoke method. Method invocation is supported only on core types in this language 
mode.
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\\.vscode\extensions\ms-dotnettool ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [dotnet-install.ps1], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage,dotnet-install.ps1
 

	at c:\Users\\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.6.0\dist\extension.js:2:4766
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by YuliiaKovalova** [comment]
Hi @ip240Z,

I assume, this issue is related to set policies on your workstation. 

Could you check your _$ExecutionContext.SessionState.LanguageMode_ in PS and share the result with us?

**Comment by YuliiaKovalova** [comment]
Feel free to reopen if it is still relevant for you.
