### ISSUE TITLE
Update repo in script's exception URLs

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/install-scripts#38]
Change repo from sdk to install-scripts under the dotnet owner in scripts' exception messages.

Example
throw "Architecture not supported. If you think this is a bug, report it at https://github.com/dotnet/sdk/issues" should be changed to throw "Architecture not supported. If you think this is a bug, report it at https://github.com/dotnet/install-scripts/issues"

**Comment by AR-May** [comment]
Fixed
