### ISSUE TITLE
vscode_intstallingdotnetruntimeerror

### ISSUE THREAD

**Issue by Muhamed4** [dotnet/install-scripts#380]
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.7.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10" -Version 7.0.10 -Runtime dotnet

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
dotnet_install: Error: Extraction failed

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.7.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10" -Version 7.0.10 -Runtime dotnet

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
dotnet_install: Error: Extraction failed

    at /home/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Acquisition/DotnetCoreAcquisitionWorker.js:90:27

**Comment by donJoseLuis** [comment]
@YuliiaKovalova 
Please note this is impacting our friends in the vscode.

- only relevant to SH on MAC (per Marc P)
- please confirm the bits for 7.0.10 dotnet are present in CLI blob for Mac
- please collect a network trace to detect where the problem is

**Comment by donJoseLuis** [comment]
@Muhamed4 greetings.
I am sorry you are experiencing this. We have had a couple of similar issues from your team recently; thus far, the root-cause has been networking for each instance.

Please consider collecting a network trace when you experience such download failures.  We have monitoring that successfully download the scripts, twice per hour. The network trace will quickly identify if the server (or edge server) served the script or of the CLI blob served the bits.

**Comment by donJoseLuis** [comment]
@Muhamed4 

We are unable to reproduce as we expected. There is something interesting about your network which is the root-cause of the problems.

We strongly encourage you get network traces of...
1. vscode download of bits via install scripts
2. stand alone install scripts getting bits from CLI blob storage

I think the above steps will quickly show you somewhere in your network is the culprit.

<img width="561" alt="MicrosoftTeams-image (1)" src="https://github.com/dotnet/install-scripts/assets/58810449/2439d954-3aba-42ac-a2aa-86220f3d5f7f">
