### ISSUE TITLE
Log checksum of targeted CLI Blob storage URIs

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/install-scripts#383]
Introduce checksum for targeted URIs in logs (PS1 & sh)

**Comment by YuliiaKovalova** [comment]
the checksum for the remote package can be extracted from https://dotnetcli.blob.core.windows.net/dotnet/checksums/7.0.11-sha.txt
 7.0.11 represents runtime version in the link

**Comment by baronfel** [comment]
We can't rely on the checksums from that location in the general case - users providing custom feed urls may be serving SDKs/Runtimes that have different content.

**Comment by YuliiaKovalova** [comment]
It will be addressed in scope of :https://github.com/dotnet/install-scripts/issues/463
