### ISSUE TITLE
Incorrect logging about size of file

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/install-scripts#391]
dotnet-install.sh incorrectly logs:
> The remote and local file sizes are not equal. Remote file size is 31367277
 bytes and local size is 31367277 bytes. The local package may be corrupted.

Caused by https://github.com/dotnet/install-scripts/pull/386/files
@YuliiaKovalova

**Comment by YuliiaKovalova** [comment]
hi @BrennanConroy,

thank you for reporting the issue, I am investigating it.

**Comment by YuliiaKovalova** [comment]
The fix was merged & deployed.
