### ISSUE TITLE
Azure Endpoint for .NET 8 WindowsDesktop Runtime Points to Outdated Version

### ISSUE THREAD

**Issue by Sewer56** [dotnet/install-scripts#395]
I'm not sure of the exact place to report it; so I apologize if this is not the right place.

I'll keep it simple.

The Azure endpoint used by the [dotnet-install](https://github.com/dotnet/install-scripts) scripts is pointing to the wrong version of the runtime for the WindowsDesktop `FrameworkName`. Which means that the install script will fetch an outdated version of this runtime if requested. For the same reason, various libraries such as my own [NetCoreInstallChecker](https://github.com/Sewer56/NetCoreInstallChecker) are affected.

Link: https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/8.0/latest.version

The URLs for main runtime and ASP.NET are up to date as expected, it's just WindowsDesktop.

This should be at RC1 instead of Preview 7, however 4 days have elapsed since RC1 release; and this endpoint has not yet unfortunately been updated; so I'm formally opening a ticket for this.

**Comment by Suchiman** [comment]
It's not just WindowsDesktop / 8.0, it also affects 7.0, e.g. https://dotnetcli.azureedge.net/dotnet/Sdk/STS/latest.version is still at `7.0.400` while it should be `7.0.401`

**Comment by YuliiaKovalova** [comment]
Hi @Sewer56,

I am looking at this issue.

**Comment by YuliiaKovalova** [comment]
Hi @Sewer56 , @Suchiman ,

Could you check if the issue is still relevant for you?

**Comment by Sewer56** [comment]
> Hi @Sewer56 , @Suchiman ,
> 
> Could you check if the issue is still relevant to you?

Appears to be updated on my end 👍

**Comment by Suchiman** [comment]
Yep, works fine now, can be closed 👍

**Comment by YuliiaKovalova** [comment]
Thank you for your cooperation with us :)
