### ISSUE TITLE
`stat` call fails on macOS when the GNU stat is used instead of BSD stat

### ISSUE THREAD

**Issue by daleeidd** [dotnet/install-scripts#396]
# Describe the bug

Get the following:
>  Error!
> .NET Acquisition Failed: Installation failed: stat: cannot read file system information for '%z': No such file or directory

## **Please attach log file(s) here if you have any:**

[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1694845816479.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/12640022/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1694845816479.txt)

Output error:
> visualstudiotoolsforunity.vstuc requested to download the .NET Runtime.
> Downloading .NET version(s) 7.0.11 ......... Error!
> Failed to download .NET 7.0.11:
> stat: cannot read file system information for '%z': No such file or directory
>
> Error!
> .NET Acquisition Failed: Installation failed: stat: cannot read file system information for '%z': No such file or directory

## Other Info:

**Reproduction Steps**

Open any C# project.

**Further technical details**

I have the GNU Tools first in my path so using their version of stat.

Stat:
> stat (GNU coreutils) 9.3
> Copyright (C) 2023 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by Michael Meskes.

VSCode
> Version: 1.81.1 (Universal)
> Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
> Date: 2023-08-09T22:20:33.924Z (1 mo ago)
> Electron: 22.3.18
> ElectronBuildId: 22689846
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Darwin arm64 22.6.0

Extension:
> 1.7.3

**Comment by baronfel** [comment]
Folks, we need to see if there's a way to detect if `stat` is GNU or BSD version - the arguments will change depending on which one we have.

**Comment by craigds** [comment]
could just hardcode the path to `/usr/bin/stat` if you always want the BSD one

**Comment by baronfel** [comment]
Closing as fixed in #397. The scripts served from the website will be updated soon.
