### ISSUE TITLE
Update the usage of cp command depending on coreutils version

### ISSUE THREAD

**Issue by f-alizada** [dotnet/install-scripts#436]
Recently there were changes in coreutils package which contains the cp command. 
starting from 9.4-3 when using `cp -n` it results warning output: 'behavior of -n is non-portable and may change in future; use --update=none instead'

For more details: 
- https://github.com/dotnet/vscode-dotnet-runtime/issues/1635
- https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62572

In order to remove the warning the cp command usage should be updated depending on the version of the cp command installed (coreutils package)

**Comment by f-alizada** [comment]
@kasperk81 it is used here: https://github.com/dotnet/install-scripts/blob/33673aca5c9c1c31d408c630f52e3886b2121c05/src/dotnet-install.sh#L964

**Comment by truboxl** [comment]
https://github.com/dotnet/install-scripts/blob/33673aca5c9c1c31d408c630f52e3886b2121c05/src/dotnet-install.sh#L947-L954

Makes no sense why only linux-musl is the exception. Should be the same for all, no?
