### ISSUE TITLE
32 bit .NET Being Installed on 64 Bit Machine

### ISSUE THREAD

**Issue by laurenprinn** [dotnet/install-scripts#44]
When a 32 bit command prompt is opened, the build downloads 32 bit dotnet even though the machine is a 64 bit. On a 32 bit command prompt the architecture is stored in two variables 
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
where as a 64 bit command prompt is stored in just one variable.
PROCESSOR_ARCHITECTURE=AMD64

This issue may be caused by the line highlighted below where the architecture is being selected by the PROCESSOR_ARCHITECTURE variable 

https://github.com/dotnet/install-scripts/blob/ede04c0065c25d30ad05ae6820ef8260c55e976c/src/dotnet-install.ps1#L158

**Comment by donJoseLuis** [comment]
@laurenprinn , thanks for the issue.  We'll take a look this week.
