### ISSUE TITLE
Install should fail on unsupported architecture levels

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/install-scripts#444]
Quite a few times, users have used `dotnet-install` on devices that only support ARMv6. For example:

* https://github.com/dotnet/runtime/issues/2817
* https://github.com/dotnet/runtime/issues/71642
* https://github.com/dotnet/runtime/issues/99249

Unfortunately, .NET requires ARMv7 and will cryptically segfault (SIGSEGV) when ran on an ARMv6 core. There are ways to [contort yourself and compile it yourself for ARMv6](https://github.com/dotnet/runtime/issues/7764#issuecomment-1043468998), but the user must be aware of this.

`dotnet-install` should verify the architectural support _level_ in addition to the architecture. In other words, it should fail to complete if the user tries to install an ARMv7-required .NET onto an ARMv6 system. This wouldn't solve the problem of users moving their file system between devices (as #&#8205;71642 above did), but it would help the vast majority of those who don't.

In addition, an override (`-f`/`--force`) command line flag should be added to bypass this lockout.

**Comment by baronfel** [comment]
I think we should do this, and I think it might even be relatively simple to add.

We check the machine architecture [here](https://github.com/dotnet/install-scripts/blob/main/src/dotnet-install.sh#L300-L325), and we could check for the versions of arm64 here, not just the presence/absence of arm.

**Comment by YuliiaKovalova** [comment]
@baronfel , sounds good, thank you!
I will take it for the current iteration.

**Comment by YuliiaKovalova** [comment]
Hi @colejohnson66,

The issue has been addressed in scope of https://github.com/dotnet/install-scripts/pull/455.
It will be available for downloading within next week.
