### ISSUE TITLE
`dotnet` segfaults after scripted install

### ISSUE THREAD

**Issue by dbarowy** [dotnet/install-scripts#459]
### Description

I just ran the [scripted install](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) on a Raspberry Pi Zero running Debian 10.  Unfortunately, `dotnet` segfaults when trying to run the binary.

```
$ .dotnet/dotnet 
Segmentation fault
```
Some system details:
```
$ file .dotnet/dotnet 
.dotnet/dotnet: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=6a504f2f11ceca0c992a01444868aeba82211931, not stripped

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ uname -a
Linux nausus 5.10.60+ dotnet/runtime#1449 Wed Aug 25 14:59:20 BST 2021 armv6l GNU/Linux
```
I recognize that this machine is a little out of date, but [all indications tell me that](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian) the machine/OS are still officially supported (for .NET 7.0).

### Reproduction Steps

I installed the .NET SDK 7.0.406 like so:
```
$ ./dotnet-install.sh --version 7.0.406
```

### Expected behavior

Minimally, `dotnet` should not segfault.

### Actual behavior

Segfaults.

### Configuration

version: .NET SDK 7.0.406
OS: Debian Buster (Raspbian)
Arch: ARM
Hardware: Raspberry Pi Zero

**Comment by YuliiaKovalova** [comment]
Hello,

The issue has been resolved in scope of https://github.com/dotnet/install-scripts/issues/444. The platforms ARMv6 and lower are not supported.
Please let me know if you have any questions.
