### ISSUE TITLE
Probable cut/paste prerequisite typo

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/install-scripts#46]
https://github.com/dotnet/install-scripts/blob/ede04c0065c25d30ad05ae6820ef8260c55e976c/src/dotnet-install.sh#L273

```
Unable to locate liblttng. Probable prerequisite missing; install libcurl
```

**Comment by bozturkMSFT** [comment]
Hi @sdmaclea , 
 Thank you for the issue. We are already tracking this in another issue: https://github.com/dotnet/install-scripts/issues/36
 So I am closing this one in favor of the other.
 Please let me know if you think these two are not duplicates.
