### ISSUE TITLE
`dot.net` is unavailable from Australia

### ISSUE THREAD

**Issue by cailyoung** [dotnet/install-scripts#460]
```
curl -vvv https://dot.net/v1/dotnet-install.sh 
*   Trying 20.236.44.162:443...
```

This eventually times out.

**Comment by cailyoung** [comment]
I have opened a ticket on services hub, ID `2404030030001082`

**Comment by YuliiaKovalova** [comment]
cc: @baronfel

**Comment by YuliiaKovalova** [comment]
Hi @mairaw,

Could you tell me if you are aware of the incident?

**Comment by YuliiaKovalova** [comment]
Hi @cailyoung,

Could you tell us if the incident is still relevant for you? Unfortunately, we don't have permissions for tracking the ticket on service hub.

cc: Hi @danzhu54,
Could you tell us if the issue was registered on your side?

Thank you!

**Comment by cailyoung** [comment]
@YuliiaKovalova it has resolved; we are still tracking on the ticket.

**Comment by mairaw** [comment]
I'd need some verbose logs in order to look into this specific issue similar to the investigation we did for https://github.com/dotnet/dnceng/issues/1372

**Comment by YuliiaKovalova** [comment]
Close the ticket since it appears to be resolved.
Feel free to reach us if you still have any questions.
