### ISSUE TITLE
dotnet-install: Failed to verify the version of installed ".NET Core SDK".

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/install-scripts#466]
I'm using the setup-dotnet Github action to install the latest 9.0 daily build.

I'm getting the error in the subject. Full log:

```
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & 'D:\a\_actions\actions\setup-dotnet\v4\externals\install-dotnet.ps1' -SkipNonVersionedFiles -Runtime dotnet -Channel LTS
dotnet-install: .NET Core Runtime with version '8.0.4' is already installed.
"C:\Program Files\PowerShell\[7](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8874728405/job/24363235450#step:2:8)\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & 'D:\a\_actions\actions\setup-dotnet\v4\externals\install-dotnet.ps1' -SkipNonVersionedFiles -Channel 9.0 -Quality daily
dotnet-install: Remote file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.5.24227.1/dotnet-sdk-9.0.100-preview.5.24227.1-win-x64.zip size is 2973106[8](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8874728405/job/24363235450#step:2:9)8 bytes.
dotnet-install: Downloaded file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.5.24227.1/dotnet-sdk-9.0.100-preview.5.24227.1-win-x64.zip size is 297310688 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Extracting the archive.
dotnet-install: Failed to verify the version of installed ".NET Core SDK".
Installation source: https://dotnetbuilds.azureedge.net/public/Sdk/[9](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8874728405/job/24363235450#step:2:10).0.100-preview.5.24227.1/dotnet-sdk-9.0.100-preview.5.24227.1-win-x64.zip.
Installation location: C:\Program Files\dotnet.
Report the bug at https://github.com/dotnet/install-scripts/issues.
Exception: D:\a\_actions\actions\setup-dotnet\v4\externals\install-dotnet.ps1:1342
Line |
1342 |      throw "`"$assetName`" with version = $($DownloadedLink.effectiveV …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ".NET Core SDK" with version = 9.0.100 failed to install with an unknown error.
Error: Failed to install dotnet, exit code: 1. dotnet-install: Failed to verify the version of installed ".NET Core SDK".
Installation source: https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.5.24227.1/dotnet-sdk-9.0.100-preview.5.24227.1-win-x64.zip.
Installation location: C:\Program Files\dotnet.
Report the bug at https://github.com/dotnet/install-scripts/issues.
Exception: D:\a\_actions\actions\setup-dotnet\v4\externals\install-dotnet.ps1:1342
Line |
1342 |      throw "`"$assetName`" with version = $($DownloadedLink.effectiveV …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ".NET Core SDK" with version = 9.0.[10](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8874728405/job/24363235450#step:2:11)0 failed to install with an unknown error.
```

FWIW, here is how my Github workflow invokes the action:

https://github.com/MichalStrehovsky/rt-sz/blob/49efb3c6bbf5eeeb3480945d26181aaac9fe5137/.github/workflows/sizestats.yml#L121-L125

Here is the failing run: https://github.com/MichalStrehovsky/rt-sz/actions/runs/8874728405/job/24363235450

This worked fine 3 days ago and I didn't make any changes in the repo for a while.

**Comment by YuliiaKovalova** [comment]
Hi @MichalStrehovsky,

According to the logs, there was a problem with checking if the package was installed **locally** successfully, after the unpacking the archive with sdk. 
Unfortunately, the normal verbosity log doesn't let me understand what kind of restrictions it may have faced.
I don't see the support of `-verbosity `parameter in the action [itself.](https://github.com/actions/setup-dotnet).

Could you just try to rerun it? Probably the was a temporary issue with the build machine.

**Comment by MichalStrehovsky** [comment]
It succeeded on a rerun. I guess since we don't have the log we won't know what went wrong and there's nothing left to investigate. Thanks!

**Comment by YuliiaKovalova** [comment]
@MichalStrehovsky, I have requested the support for the scripts verbosity output.
Once available, you can enable it by default: https://github.com/actions/setup-dotnet/issues/522

**Comment by LoopedBard3** [comment]
Hello @YuliiaKovalova, I am still seeing this issue when running the command line: `powershell.exe -NoProfile -ExecutionPolicy Bypass .\dotnet-install.ps1 -InstallDir .\plz_dlt -Architecture x64 -Channel 9.0 -Quality daily` on windows. The full execution is as follows:
```
powershell.exe -NoProfile -ExecutionPolicy Bypass .\dotnet-install.ps1 -InstallDir .\plz_dlt -Architecture x64 -Channel 9.0 -Quality daily
dotnet-install: Remote file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.5.24230.7/dotnet-sdk-9.0.100-preview.5.24230.7-win-x64.zip size is 295722648 bytes.
dotnet-install: Downloaded file https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.5.24230.7/dotnet-sdk-9.0.100-preview.5.24230.7-win-x64.zip size is 295722648 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Extracting the archive.
dotnet-install: Failed to verify the version of installed ".NET Core SDK".
Installation source: https://dotnetbuilds.azureedge.net/public/Sdk/9.0.100-preview.5.24230.7/dotnet-sdk-9.0.100-preview.5.24230.7-win-x64.zip.
Installation location: .\plz_dlt.
Report the bug at https://github.com/dotnet/install-scripts/issues.
".NET Core SDK" with version = 9.0.100 failed to install with an unknown error.
At C:\Users\parkerbibus\Desktop\dotnet-install.ps1:1355 char:5
+     throw "`"$assetName`" with version = $($DownloadedLink.effectiveV ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (".NET Core SDK"... unknown error.:String) [], RuntimeException
    + FullyQualifiedErrorId : ".NET Core SDK" with version = 9.0.100 failed to install with an unknown error.
```

Is there any other steps we can take to hopefully figure out why this is failing?

**Comment by YuliiaKovalova** [comment]
Hi @MichalStrehovsky ,

Could you please rerun it with `-Verbose` argument specified and attach the log?

Thank you!

**Comment by YuliiaKovalova** [comment]
We were able to reproduce it on our side, I am working on the resolution.

**Comment by ViktorHofer** [comment]
@mmitche submitted [a change](https://github.com/dotnet/sdk/pull/40580) that will fix this but the change hasn't yet reached installer because dependency flow is blocked right now because of a source-build re-bootstrap issue. Once that is resolved, bits should be flowing again and the blob won't contain duplicate assets anymore.

You can the track the status of dependency flow via this PR: https://github.com/dotnet/installer/pull/19634

**Comment by mmitche** [comment]
My change should have resolved the issue immediately (since it affected sdk's official builds immediately). If you see this again, let us know

**Comment by mmitche** [comment]
Looking closer, the main build is broken, this change https://github.com/dotnet/installer/pull/19641 will end up being the resolution.

**Comment by YuliiaKovalova** [comment]
@mmitche, I have just validated the fix - it works now!
Thank you for addressing it.
