### ISSUE TITLE
Install SDK respecting global.json configuration

### ISSUE THREAD

**Issue by mattinsp** [dotnet/install-scripts#476]
### Is your feature request related to a problem? Please describe.
The dotnet CLI should allow installation of SDK versions respecting the configuration in global.json.

### Describe the solution you'd like
`dotnet sdk install <version>` - version should be optional and omitting it should utilise the global.json file.

### Additional context
[dotnet-install.ps1.](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) exists and allows a `jsonfile` to be set but this does not respect the "rollForward" configuration which significantly limits its use.

**Comment by marcpopMSFT** [comment]
Moving since the request is related to the install scripts. We are looking into CLI commands for update/install but those will come in a future release.

**Comment by YuliiaKovalova** [comment]
Hi @baronfel ,

Could you please to prioritize this work?
Thank you!

**Comment by mattinsp** [comment]
> Moving since the request is related to the install scripts. We are looking into CLI commands for update/install but those will come in a future release.

The problem and requested solution clearly indicate that this is about the dotnet CLI, why was this moved?

**Comment by YuliiaKovalova** [comment]
> > Moving since the request is related to the install scripts. We are looking into CLI commands for update/install but those will come in a future release.
> 
> The problem and requested solution clearly indicate that this is about the dotnet CLI, why was this moved?

cc: @marcpopMSFT

**Comment by mattinsp** [comment]
@YuliiaKovalova  I believe https://github.com/dotnet/install-scripts/issues/468 addresses this issues with the install scripts which is good to see, but this also needs implementation in the dotnet CLI of course.

**Comment by marcpopMSFT** [comment]
I moved it as I took the additional context to be about supporting rollforward in the install scripts. It's true that there is also a suggestion to have this capability in the dotnet CLI which would live in the sdk repo but we have an issue tracking improving the acquisition already:
https://github.com/dotnet/sdk/issues/14960

So I think since we have 14960 and 468, perhaps this issue can be closed and tracked there?

**Comment by YuliiaKovalova** [comment]
Expected work from install-scripts side will be handled in scope of 
https://github.com/dotnet/install-scripts/issues/468
