### ISSUE TITLE
Publish install scripts to blob storage

### ISSUE THREAD

**Issue by richlander** [dotnet/install-scripts#489]
The install scripts are currently part of our [marketing site](https://dotnet.microsoft.com). Given #487, one can conclude that current practice is an anti-pattern. In general, our marketing site should be an excellent discovery mechanism for assets deployed elsewhere.

Please consider publishing install scripts to Azure blob storage and then use the marketing site as a discovery mechanism for that.

**Comment by baronfel** [comment]
cc @rbhanda for that one - he has all the keys to the various places that the scripts go.

**Comment by richlander** [comment]
302 FTW!

**Comment by richlander** [comment]
Closing this as dupe.
