### ISSUE TITLE
dotnet-install.ps1 doesn't handle global.json that contains comments

### ISSUE THREAD

**Issue by pieandcakes** [dotnet/install-scripts#49]
This is an issue when using dotnet-install.ps1 to install the dotnet SDK. When running `restore` or  building, the comment is handled just fine.

Offending Line: 
https://github.com/dotnet/sdk/blob/dc6a9b177858767908fa68cb6677adca278ac1ec/scripts/obtain/dotnet-install.ps1#L314 

Possible Fix:
` ((Get-Content .\global.json) -replace '^\s*//.*' | ConvertFrom-Json).sdk.version //This removes comments during parsing`

example global.json:
```
{
  "sdk": {
    // Need to use a particular version to ensure consistency across machines no matter what SDK versions they have installed.
    "version": "3.1.201"
  }
}
```

**Comment by bozturkMSFT** [comment]
Hi @pieandcakes . Thank you for the issue.

 `dotnet restore` may be fine with it, but JSON file format does not allow comments. We are also trying to keep the scripts as simple as possible.

 Can you instead use a new property like this:

```
{
  "sdk": {
    "comment": "Need to use a particular version to ensure consistency across machines no matter what SDK versions they have installed."
    "version": "3.1.201"
  }
}
```

**Comment by pieandcakes** [comment]
@bozturkMSFT Hi, Its not my global.json, but I'll make the suggestion. If I build/run with that comment but run dotnet-install separately, everything else handles the comment fine except the script.
