### ISSUE TITLE
IBM Power architecture not detected

### ISSUE THREAD

**Issue by barf** [dotnet/install-scripts#498]
Hello
On FreeBSD 15.0-CURRENT here, msbuild fails to build because `src/dotnet-install.sh` does not correctly detect IBM Power architecture (Mono and xbuild etc is working on this arch).

It was trivial to fix the script however more work is required to bring up dot net on this architecture, the pull request is here:
https://github.com/dotnet/install-scripts/pull/497

**Comment by YuliiaKovalova** [comment]
@barf , thank you for the contribution, we will deploy the change next week.
