### ISSUE TITLE
Unable to reach https://dot.net/v1/dotnet-install.sh 

### ISSUE THREAD

**Issue by JR-Morgan** [dotnet/install-scripts#499]
Having an issue where requesting https://dot.net/v1/dotnet-install.sh results in a connection timeout.

This command:
`curl -SL https://dot.net/v1/dotnet-install.sh`
results in the following: 
`curl: (28) Failed to connect to dotnet.microsoft.com port 443 after 130337 ms: Connection timed out`

In addition to this, opening this the URL in Safari and Brave gives a similar Connection Timeout, while Google Chrome, Firefox, and Edge appear to download the file almost immediately.

**Comment by JR-Morgan** [comment]
I see some discussion on #490 r.e. moving these scripts? has this been done yet? is there another url I should be using?

**Comment by baronfel** [comment]
No motion on that issue since the initial flurry of activity, I'll poke the conversation internally again

**Comment by JR-Morgan** [comment]
Ok, my issue seems resolved now.
I'm thinking this was related to the timeouts that was affecting Microsoft yesterday (Tracking IDL KTY1-HW8)
https://azure.status.microsoft/en-gb/status/history/

The `https://dot.net/v1/dotnet-install.sh` was super slow to respond and was causing our CI to fail consistently.
