### ISSUE TITLE
[dotnet-install.ps1] Incorrect auto architecture when running from Powershell classic on Windows ARM64 

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/install-scripts#51]
When running `dotnet-install.ps1` from Powershell classic on Windows ARM64 without an `-Architecture` specified, the installer will resolve to downloading an `x86` build of the sdk. 

The reason seems to be [this line](https://github.com/dotnet/install-scripts/blob/ede04c0065c25d30ad05ae6820ef8260c55e976c/src/dotnet-install.ps1#L158), Powershell classic runs as emulated x86 so the return value is, accordingly, `x86`. As expected, the issue does not impact powershell core.

We should probably update the script so that the processor architecture is determined via different means. One potential solution is using the windows command `wmic OS get OSArchitecture`, which reports the correct OS architecture. If you agree with this solution I could perhaps try to contribute a PR that fixes the problem.

We've been seeing this issue in the windows arm64 builds of `dotnet/runtime`, which is using `dotnet-install.ps1` and powershell classic to download its bootstrapping sdk. cc @safern @ViktorHofer

**Comment by eiriktsarpalis** [comment]
Actually, there seems to be an even simpler solution:
```
[System.Environment]::GetEnvironmentVariable("PROCESSOR_ARCHITECTURE", [System.EnvironmentVariableTarget]::Machine)
```

**Comment by safern** [comment]
cc: @jjmew

**Comment by jjmew** [comment]
@bozturkMSFT Is this something your team owns? The project System is not involved on this.

**Comment by bozturkMSFT** [comment]
@jjmew Yes, we own the scripts. @eiriktsarpalis Thank you for the issue. We are already tracking this here https://github.com/dotnet/install-scripts/issues/44 . We are trying to make sure we don't break anyone's builds that are relying on this wrong behavior. After that, the fix will be available in the website.
