### ISSUE TITLE
Feature request: dotnet-install script option to print out the path it installed to

### ISSUE THREAD

**Issue by JayBazuzi** [dotnet/install-scripts#518]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I wish for a way to print the path to the installed SDK, and nothing else, similar to:

```
$dotnet_sdk_path = $( dotnet-install-sh --print-sdk-path )
```

## Details

My repo uses `global.json` to specify `sdk.version`:

```json
{
    "sdk": {
        "version": "9.0.100-preview.6.24328.19",
        "rollForward": "disable"
    }
}
```

And my build script looks like:

```bash
curl -sSL https://dot.net/v1/dotnet-install.sh | bash -s -- --jsonfile global.json
export PATH="$HOME/.dotnet/sdk/9.0.100-preview.6.24328.19/:$PATH"

dotnet test
```

With this feature my build script could be simplified to:

```
$dotnet_sdk_path = $( curl -sSL https://dot.net/v1/dotnet-install.sh | bash -s -- --jsonfile global.json --print-sdk-path )
export PATH="$dotnet_sdk_path:$PATH"

dotnet test
```

**Comment by MichalPavlik** [comment]
Hi, the PATH should be updated automatically (unless no_path is set): https://github.com/dotnet/install-scripts/blob/19141c154c69240477c47c60af9e1597ee13697b/src/dotnet-install.sh#L1861

**Comment by JayBazuzi** [comment]
> the PATH should be updated automatically

That only applies if the script is dot-sourced.

**Comment by MichalPavlik** [comment]
Yes. If it's not an option for you, is the ability to set the path in advance with the `--install-dir` parameter sufficient?

**Comment by JayBazuzi** [comment]
Not really. To use `--install-dir` I'd need to pick a destination correctly, which is logic that already exists in dotnet-install and I'd hate to have to re-implement it.

**Comment by JayBazuzi** [comment]
If I could wave a magic wand, I would:
- remove the ability to dot-source dotnet-install.sh
- add a `--print-sdk-path` option

This would simplify the script overall, address my needs, and eliminate the other two Issues I opened (#519 #520), but that would be a breaking change so maybe you don't want to do that.

**Comment by MichalPavlik** [comment]
> Not really. To use `--install-dir` I'd need to pick a destination correctly, which is logic that already exists in dotnet-install and I'd hate to have to re-implement it.

I'm not sure I understand. You can pick any destination directory to be able to run `dotnet`.

```bash
mipavlik@Microsoft-Work:~$ dotnet --info

Command 'dotnet' not found, but can be installed with:

sudo snap install dotnet-sdk

mipavlik@Microsoft-Work:~$ ./dotnet-install.sh --install-dir ~/my-sdk-installation
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.402/dotnet-sdk-8.0.402-linux-x64.tar.gz
dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.402/dotnet-sdk-8.0.402-linux-x64.tar.gz size is 211866121 bytes.
dotnet-install: Extracting archive from https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.402/dotnet-sdk-8.0.402-linux-x64.tar.gz
dotnet-install: Downloaded file size is 211866121 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Installed version is 8.0.402
dotnet-install: Adding to current process PATH: `/home/mipavlik/my-sdk-installation`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
mipavlik@Microsoft-Work:~$ dotnet --info

Command 'dotnet' not found, but can be installed with:

sudo snap install dotnet-sdk

mipavlik@Microsoft-Work:~$ export PATH="~/my-sdk-installation:$PATH"
mipavlik@Microsoft-Work:~$ dotnet --info
.NET SDK:
 Version:           8.0.402
 Commit:            70aa751718
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad
.......
```

As you can see, I didn't dot-sourced the script, but I explicitly set the directory and added the same directory to the PATH variable. Then I was successfully started the `dotnet` app.

**Comment by JayBazuzi** [comment]
I like the idea of allowing dotnet-install to install dotnet to its default cache location, because I don't want to do cache management myself.

Suppose I use `--install-dir ~/my-sdk-installation` and then I update to a newer version of dotnet. Do I:
- every time my script runs, I must first delete `~/my-sdk-installation` and redownload it (slow)
- I have to remember to delete `~/my-sdk-installation` when updating dotnet (unreliable)
- Pick an install dir that includes the dotnent version (oof)
- something else?

I suspect this conversation is missing some shared context/understanding, hope we can get to the bottom of it.

**Comment by MichalPavlik** [comment]
If you don't specify the `--install-dir`, the default value is `$HOME/.dotnet` for Linux/MacOS. I don't think we will change this default (these scripts are in maintenance mode), so you can safely update PATH variable based on that information.

When you update to a newer version of dotnet, the script will install new SDK side-by-side with the older version. You don't have to delete anything, unless you want to save some space. But this behavior is same regardless of `--install-dir` value.

It's possible there is a missing understanding from my side. @baronfel, your thoughts/perspective would be valuable here :)

**Comment by JayBazuzi** [comment]
FYI I have modified my original post to add this to `global.json`:

```json
        "rollForward": "disable"
```

**Comment by JayBazuzi** [comment]
I can see now that I was confused in several ways, and I may not have explained the need very well.

I was hoping that `~/.dotnet/dotnet` would be versioned along with everything else, but it sounds like that file is unversioned. Is that correct?

**Comment by JayBazuzi** [comment]
I highly value reproducible and hermetic builds and other processes.
 * If it works in a particular way today, I want it to work in the exact same way in the future, including using the exact same versions of all dependencies. I want dependency versions to be exactly locked now, and then I'll take dependency updates through some other process (like dependabot).
 * If I have two repositories on the same machine, I want them to be able to use different versions of each dependency without stepping on each others' toes.

For now I am switching to:

```bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

curl --fail --silent --location https://dot.net/v1/dotnet-install.sh | bash -s -- --jsonfile global.json --install-dir "${SCRIPT_DIR}/.dotnet" > /dev/null
export PATH="${SCRIPT_DIR}/.dotnet:${PATH}"

dotnet ...
```

**Comment by MichalPavlik** [comment]
> I was hoping that ~/.dotnet/dotnet would be versioned along with everything else, but it sounds like that file is unversioned. Is that correct?

I can't guarantee it's not versioned. The executable is part of the package. I guess this simple host loads the CoreCLR and invokes .NET type entry point with parameters passed to the `dotnet`. The .NET code invoked in this host process is most probably SDK version dependent. These details could be answered more precisely by the SDK team.

I understand that stable build environment is important to you. You can instruct the script to install particular version of SDK via parameters or `global.json` as you did in the last post. When script detects that you already have a target SDK version installed, it will do essentially nothing, so it's safe to execute the script multiple times without causing any change.

**Comment by JayBazuzi** [comment]
OK. As I understand it now, my original feature request doesn't make sense. Thanks for talking me through it.
