### ISSUE TITLE
Unable to install 9.0 on a Raspberry Pi

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/install-scripts#538]
I'm trying to load .Net 9 onto a Raspberry Pi device.  I grabbed the script and, per @333fred on the C# Discord, told it:
```
./dotnet-install.sh --channel 9.0 --quality preview --runtime dotnet
```

It immediately errored out with:
```
dotnet-install: Error: failed to locate the latest version in the channel '9.0' with 'preview' quality for 'dotnet-runtime', os: 'linux', architecture: 'arm64'.
```

Fred said this is likely an error in the script, and to report it here.

**Comment by JanProvaznik** [comment]
Could you please run the command with `--verbose` flag and paste the output here? I don't have a Raspberry Pi device on me so I'm unable to validate if it's an error on our side or investiagate what goes wrong.

**Comment by JanProvaznik** [comment]
stale
