### ISSUE TITLE
dotnet-install.ps1 causes hash mismatch error

### ISSUE THREAD

**Issue by kit494way** [dotnet/install-scripts#541]
Executing dotnet-install.ps1 which is download from https://dot.net/v1/dotnet-install.ps1 causes hash mismatch error.

```sh
$ .\dotnet-install.ps1 -Channel 7.0 -DryRun
.\dotnet-install.ps1: File C:\Users\kita9\dotnet-install.ps1 cannot be loaded. The contents of file C:\Users\kita9\dotnet-install.ps1 might have been changed by an unauthorized user or process, because the hash of the file does not match the hash stored in the digital signature. The script cannot run on the specified system. For more information, run Get-Help about_Signing..
```

**Comment by JanProvaznik** [comment]
I suspect https://learn.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/signed-powershell-script-fails-hash-mismatch .
Do you have other than en-US locale?

**Comment by kit494way** [comment]
Yes, I use ja-JP locale.

**Comment by kit494way** [comment]
Thanks. I confirm that the issue has been resolved.
