### ISSUE TITLE
The latest released version of .NET desktop runtime is being reported as 9.0.0-rc.2.24474.4 instead of 9.0.0

### ISSUE THREAD

**Issue by remco1271** [dotnet/install-scripts#549]
https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/9.0/latest.version URL is returning 9.0.0-rc.2.24474.4 instead of 9.0.0
Same as #548 but different URL.

**Comment by JanProvaznik** [comment]
@rbhanda 
Please also check the ASP runtime (I'm not sure about the link).

**Comment by remco1271** [comment]
ASP runtime looks good: `9.0.0` https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/9.0/latest.version

**Comment by timlajaunie** [comment]
"[LTS](https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/LTS/latest.version)" and "[8.0](https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/8.0/latest.version)" channels are currently reporting 8.0.8, when the latest is actually 8.0.11.  It seems the desktop runtime version began to lag all together at some point.

**Comment by Sewer56** [comment]
Here's the data formatted as a table:

| Architecture | Format     | Download URL |
|--------------|------------|--------------|
| AMD64        | Archive    | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-x64.zip |
| AMD64        | Executable | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-x64.exe |
| x86          | Archive    | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-x86.zip |
| x86          | Executable | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-x86.exe |
| ARM          | Archive    | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-arm.zip |
| ARM          | Executable | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-arm.exe |
| ARM64        | Archive    | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-arm64.zip |
| ARM64        | Executable | https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0-rc.2.24474.4/windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-arm64.exe |

Current API response in table format.

This happened last year too:
- https://github.com/dotnet/install-scripts/issues/395

In that case, it was resolved by @YuliiaKovalova at the time

**Comment by JanProvaznik** [comment]
@Sewer56 Where are you getting the link to these RC2 files?
I see that https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/9.0/latest.version still points to a wrong version but the install scripts construct the correct version when installing.
E.g. `dotnet-install.ps1' -Channel 9.0 -Runtime windowsdesktop -Architecture arm64 -Verbose`

> VERBOSE: dotnet-install: Retrieving primary payload URL from aka.ms link for channel: '9.0', quality: '' product: 'windowsdesktop-runtime', os: 'win', architecture: 'arm64'.
> VERBOSE: dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/9.0/windowsdesktop-runtime-win-arm64.zip'.
> ...
>   Location: https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/9.0.0/windowsdesktop-runtime-9.0.0-win-arm64.zip

Same for LTS, STS, 8.0

**Comment by JanProvaznik** [comment]
The file downloading issue has been resolved and everything updated. Note that you might need to go to private mode to check because the browsers cache the results.

https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/9.0/latest.version
https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/9.0/latest.version
https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/9.0/latest.version

**Comment by Sewer56** [comment]
Looks good to me
