### ISSUE TITLE
dotnet-install.sh dependency checks are incorrect

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/install-scripts#6]
When I build the coreclr component, I get `dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.` soon after the script starts running, even though I do have zlib installed and the build finishes without any error. 

This also appears to be happening in CI builds as well, as can be seen here: https://dev.azure.com/dnceng/public/_build/results?buildId=614751&view=logs&j=2336a351-be5a-5f79-bbfa-f7a178b0fa04&t=faf0c5b5-f158-5102-6aff-48775dc0e8ed&l=24

It seemed to not cause any problems, but it's odd to see the warning there.

**Comment by donJoseLuis** [comment]
The need tracked in this issue should is tracked as a lower priority item under the re-engineering effort. Moving to the re-engineering project.

**Comment by donJoseLuis** [comment]
Tracking the "requiring of tools that are not needed" separately, in #36

**Comment by yatli** [comment]
Should be `grep libz` instead of `grep zlib`?

```
(base) yatli@MININT-MJGVNFB:/usr/lib$ dpkg-query -L zlib1g
/.
/lib
/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu/libz.so.1.2.11
/usr
/usr/share
/usr/share/doc
/usr/share/doc/zlib1g
/usr/share/doc/zlib1g/changelog.Debian.gz
/usr/share/doc/zlib1g/copyright
/lib/x86_64-linux-gnu/libz.so.1
```

**Comment by Cuniq** [comment]
@yatli changing zlib to libz solved everything

**Comment by anirugu** [comment]
Does anyone know how  to fix it, I am not able to install either zlib or libz. same for the command given to all package. How I can solve it on ubuntu 20.

**Comment by Cuniq** [comment]
@anirugu try sudo apt install zlib1g

**Comment by Ryazbeck** [comment]
> @anirugu try sudo apt install zlib1g

I installed zlib1g and still can't find it.

> pi@raspberrypi:~/runner/src$ ./dev.sh layout
> ~/runner/src ~/runner/src
> 
> 
> -----------------------------------------
>   Ensure Dotnet SDK
> -----------------------------------------
> Download dotnetsdk into /home/pi/runner/src/../_dotnetsdk/3.1.100
> dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.

**Comment by danmosemsft** [comment]
I have done `sudo apt install zlib1g` and that is probably correct per @Cuniq above and the documentation [here](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies)

However the script checks with `ldconfig -v | grep zlib` and that does not appear to find it. I am guessing this is expected.

In general as pointed out above the script does not check for everything required
https://github.com/dotnet/install-scripts/blob/master/src/dotnet-install.sh#L270-L274
\eg for Ubuntu they are listed here
https://github.com/dotnet/install-scripts/blob/master/src/dotnet-install.sh#L270-L274

The title of this issue should perhaps be "dotnet-install.sh dependency checks are incorrect"

**Comment by SamuelJohnsonMedia** [comment]
This needs resolving on Github Actions too.

**Comment by AR-May** [comment]
The installation script does not resolve dependencies, so this warning is a part of the dependencies check. It concerns dotnet, not the script itself, so there is no reason for the script to fail. 

Dependencies check indeed has problems. We decided to remove it and instead always ask the customer to visit the documentation page and to check the dependencies listed there.

**Comment by AR-May** [comment]
@SamuelJohnsonMedia, is there anything we can do to help you with this:
>  This needs resolving on Github Actions too.

Or this is something your team can fix internally?

**Comment by SamuelJohnsonMedia** [comment]
> Or this is something your team can fix internally?

Not something we can fix; its an issue with the GitHub action as it emits this warning when using the script on Ubuntu 18.04:
```
/home/runner/work/_actions/actions/setup-dotnet/v1.7.2/externals/install-dotnet.sh --version 5.0.100-rc.2.20479.15
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.2.20479.15/dotnet-sdk-5.0.100-rc.2.20479.15-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.2.20479.15/dotnet-sdk-5.0.100-rc.2.20479.15-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
/home/runner/.dotnet:/opt/hostedtoolcache/node/12.19.0/x64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

On Ubuntu 20 we get an additional warning:
```
/home/runner/work/_actions/actions/setup-dotnet/v1.7.2/externals/install-dotnet.sh --version 5.0.100-rc.2.20479.15
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet_install: Warning: Unable to locate liblttng. Probable prerequisite missing; install libcurl.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.2.20479.15/dotnet-sdk-5.0.100-rc.2.20479.15-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.2.20479.15/dotnet-sdk-5.0.100-rc.2.20479.15-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
/home/runner/.dotnet:/opt/hostedtoolcache/node/12.19.0/x64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by AR-May** [comment]
I see. Well, I suppose we do not hit this issue with GitHub actions anymore: these were only warnings that we showed and now they are removed.
