### ISSUE TITLE
SDK version parsing from global.json is not working on macOS

### ISSUE THREAD

**Issue by kondratyev-nv** [dotnet/install-scripts#61]
This is the same problem as in https://github.com/dotnet/sdk/pull/12339.

Running install script `dotnet-install.sh` with `jsonfile` argument works on macOS only when `sdk` section has a single property `version`. When `sdk` section has multiple properties, for example,
```json
"sdk": {
    "version":  "5.0.100-preview.6.20310.4",
    "allowPrerelease": true,
    "rollForward": "major"
  }
```
a version is detected as `5.0.100-preview.6.20310.4allowPrerelease:truerollForward:major`.
Also, in a case when `version` is not the first property in `sdk` a version can not be detected returning an error ``dotnet_install: Error: Unable to find the SDK:version node in `global.json` ``.

**Comment by kondratyev-nv** [comment]
I can create a similar PR as https://github.com/dotnet/sdk/pull/12339. However, `./build.sh` from the root of the repo throws and error, and I don't see tests (as in https://github.com/dotnet/sdk/blob/master/src/Tests/InstallationScript.Tests/GivenThatIWantToInstallTheSdkFromAScript.cs) to make sure that changes are working.

**Comment by donJoseLuis** [comment]
Greetings @kondratyev-nv , thanks for creating the issue. We currently have #7 tracking the same problem, which we've already triaged and placed properly on our backlog.  Please track that instead, as we'll close this one to have a trimmed overall backlog.
