### ISSUE TITLE
`-Channel master -Version coherent` downloads 3.0, not 5.0

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/install-scripts#64]
Is that right? If I remove "-Version coherent" it tries to get 5.0. 3.0 isn't even in support anymore.

```
C:\git\performance>curl -o dotnet-install.ps1 https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 39736 100 39736 0 0 39736 0 0:00:01 --:--:-- 0:00:01 497k

C:\git\performance>powershell.exe -NoProfile -ExecutionPolicy Bypass dotnet-install.ps1 -InstallDir C:\git\performance\tools\dotnet\x64 -Architecture x64 -Channel master -Version coherent
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview-009817/dotnet-sdk-3.0.100-preview-009817-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview-009817/dotnet-sdk-3.0.100-preview-009817-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\git\performance\tools\dotnet\x64\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
```

**Comment by bozturkMSFT** [comment]
Hi @danmosemsft ,
 Thanks for the issue. Install scripts rely on `latest.coherent.version` file to determine the latest coherent build, but the file hasn't been updated since 2018. It still points to 3.0 build in the logs you shared.
 At the moment, I don't know why it is no longer being generated. I will investigate more and post updates here.

**Comment by danmosemsft** [comment]
OK thanks @bozturkMSFT . Maybe it isn't meaningful anymore -- I was just trying to work around the other issue I logged

**Comment by bozturkMSFT** [comment]
@KathleenDollard We have decided to drop support for downloading `coherent` versions using `-version` option.
