### ISSUE TITLE
Using `--jsonfile` switch of `dotnet-install.sh` fails with some roll forward policy

### ISSUE THREAD

**Issue by atifaziz** [dotnet/install-scripts#71]
I have a project with the following `global.json`:

```json
{
  "sdk": {
    "version": "3.1.101",
    "rollForward": "latestFeature"
  }
}
```

Using [`dotnet-install.sh`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) with the `--jsonfile` option produces an invalid download URL of the form: `https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.101rollForward:latestFeature/dotnet-sdk-3.1.101rollForward:latestFeature-linux-musl-x64.tar.gz`

The problem is the `3.1.101rollForward:latestFeature` path component of the URL.

Steps to reproduce in a Docker container running Alpine Linux 3.9:

```
❯ docker run --rm -it alpine:3.9
/ # apk add --no-cache -q bash
/ # wget -q https://dot.net/v1/dotnet-install.sh
/ # chmod +x dotnet-install.sh
/ # cat > global.json <<EOF
> {
>   "sdk": {
>     "version": "3.1.101",
>     "rollForward": "latestFeature"
>   }
> }
> EOF
/ # ./dotnet-install.sh --jsonfile global.json --dry-run
dotnet-install: Payload URLs:
dotnet-install: Primary named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.101rollForward:latestFeature/dotnet-sdk-3.1.101rollForward:latestFeature-linux-musl-x64.tar.gz
dotnet-install: Repeatable invocation: ./dotnet-install.sh --version "3.1.101rollForward:latestFeature" --install-dir "/root/.dotnet" --architecture "x64"
```

**Comment by bozturkMSFT** [comment]
Hi @atifaziz ,
 Thank you for the issue. Since we are already tracking this in https://github.com/dotnet/install-scripts/issues/7, I will close this one.

**Comment by atifaziz** [comment]
@bozturkMSFT Thanks for pointing me to the already logged issue and apologies for the duplicate (search failed me).
