### ISSUE TITLE
Provide a way to download latest public release of a given preview

### ISSUE THREAD

**Issue by tannergooding** [dotnet/install-scripts#74]
Currently the install script provides ways to easily download the Current, LTS, a given RTM release (such as 3.1), or a given branch (such as release/5.0.1xx-preview7). However, it does not provide an easy way to download a latest public preview such as `5.0 Preview 8`.

Due to how various things are setup, the latest branch may not exactly match the publicly released bits or may not be available. This is currently the case with `release/5.01xx-preview8` where the build fails to download or with `release/5.01xx-preview7` where the branch version is ahead of the publicly released version.

This can make it very difficult to consume the latest preview from CI or through something like the `setup-dotnet` GitHub Action.

**Comment by tannergooding** [comment]
A possible option would be to allow `--channel 5.0 --version preview8`, where `--channel 5.0` would by default get the latest (either preview or stable release).

**Comment by tannergooding** [comment]
CC. @mmitche, @leecow, @rbhanda

**Comment by rbhanda** [comment]
If you are looking to download latest public release, the steps can be found in [release notes](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.8-install-instructions.md)
Are you looking for https://aka.ms/install-dotnet-preview to install latest releases for .NET 5?

**Comment by tannergooding** [comment]
I'm looking to do this via the general purpose dotnet-install script, so I dont need to support multiple things in my CI and so I can set a specific preview that wont roll forward until I've submitted a PR moving to the next.

The install script already works for other scenarios, just not readily with preview releases and the branches dont always work, as called out above.

**Comment by bozturkMSFT** [comment]
@tannergooding Though this requires some additional work for you, I believe you can fetch and parse [releases.json](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json) to learn the latest publicly available version and request it from the install scripts.

 This feature can also be built into the scripts, of course. However, we are focusing on improving the resiliency and fixing high priority bugs at the moment. Looking at our current roadmap, it appears that we won't be able to deliver this in the near future.

**Comment by mmitche** [comment]
For .NET 6, at some point in the preview cycle, we're going to drop the version suffix (release as 6.0.100-preview.1/6.0.0-preview.1 instead of 6.0.100-preview.1.1234.5). That may make this easier, since all you'll need to know is the preview number you want to install.

**Comment by bozturkMSFT** [comment]
I'm closing this as this will be implemented as part of issue https://github.com/dotnet/install-scripts/issues/12
