### ISSUE TITLE
dotnet-install.sh causes weird behavior with Linux filesystem

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/install-scripts#80]
When we switched to running our tests on Helix we noticed a bunch of tests became flaky due to timeouts. After a bunch of investigation it was found that using dotnet-install.sh to get the Runtime and SDK and then running tests that wrote logs to disk would result in pauses up to 30 seconds long which triggered timeouts we have. If the machine already had the Runtime and SDK installed no issues were seen.

The fix was to call `sync` after using the dotnet-install.sh script, but it would probably be better if the script itself did this.
https://github.com/dotnet/aspnetcore/blob/d69a2253bb26b07290de3a7aa8d3bad54c610dfb/eng/helix/content/runtests.sh#L85-L86

**Comment by bozturkMSFT** [comment]
Hi @BrennanConroy,
 Thank you for the issue. We believe this is out of the script's scope. Let us know if you strongly disagree.
