### ISSUE TITLE
DotNet Install scripts will now support a productVersion.txt allowing custom version on installation

### ISSUE THREAD

**Issue by MattGal** [dotnet/install-scripts#85]
# DotNet Install scripts will now support a productVersion.txt allowing custom version on installation

This change is already in use inside .NET Core repos which use the common 'Arcade' infrastructure. It was added to allow servicing exercises where "stable" versions of .NET Core Runtimes and SDKs could be produced repeatedly without any special tricks to prevent these candidate stable builds from colliding when uploading builds.  Once a candidate build is deemed sufficient for release, it thus has only to be copied to a new path to become an "official" release.

## Discussion
Please share your thoughts on this change using this issue.  I'll be trying merge the PR listed above sometime week of 10/5.

## Details

- See https://github.com/dotnet/install-scripts/pull/76 for context.

- At some point we may also want to leave behind a text file describing the mapping between an given non-stable version with the stable version files it contained (e..g. the mapping from "5.0.100-rtm.20471.12" -> "5.0.100", to enable Arcade scripts and other automation to detect that this has happened and to calculate the correct path later.  This is not currently blocking so is something we may not actually do.

- Related: https://github.com/dotnet/install-scripts/issues/65

@richlander , @mmitche  FYI.

**Comment by bozturkMSFT** [comment]
The related PR https://github.com/dotnet/install-scripts/pull/76 is merged, closing.
