### ISSUE TITLE
Install script fails trying to download release/5.0.1xx

### ISSUE THREAD

**Issue by adegeo** [dotnet/install-scripts#87]
Using the install script to install the latest 5.0 release is suddenly failing. Using this command line:

```powershell
.\dotnet-install.ps1 -InstallDir "c:\program files\dotnet" -Channel "release/5.0.1xx"
```

Results in this file trying to download and it doesn't exist: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rtm.20515.10/dotnet-sdk-5.0.100-rtm.20515.10-win-x64.zip

**Comment by mmitche** [comment]
Caused by stabilization. You need an updated install script: https://github.com/dotnet/install-scripts/blob/master/src/dotnet-install.ps1

That said, you may have trouble using this as there will be a number of nuget feeds required to make it workable.

**Comment by adegeo** [comment]
I'll check if it's fixed. Where we noticed this is from our github action workflow which downloads the script during the action and runs it. It uses https://dot.net/v1/dotnet-install.ps1 to download. So AFAIK it should always be the latest.

**Comment by bozturkMSFT** [comment]
Related changes to the install scripts have been pushed to dotnet.microsoft.com, but they are not deployed yet. Please track the status here: https://github.com/dotnet/website/pull/2372
