### ISSUE TITLE
Script fails to access the feed if TLS1.2 is not enabled

### ISSUE THREAD

**Issue by wli3** [dotnet/install-scripts#9]
https://twitter.com/dotMorten/status/1246109315624095744

![image](https://user-images.githubusercontent.com/6993335/78601832-4a503d00-780a-11ea-9402-e9af53956669.png)

**Comment by bozturkMSFT** [comment]
Hi @donMorten, 
 Can you run [this version](https://github.com/dotnet/install-scripts/blob/dev/bozturk/enable-tls12/src/dotnet-install.ps1) with `-EnableTls` flag and let me know if it fixes the issue?

**Comment by dotMorten** [comment]
@bozturkMSFT Thanks but I'm getting: "The property 'Tls13' cannot be found on this object. Verify
that the property exists."

**Comment by dotMorten** [comment]
...if I comment out line 567, it works!

**Comment by bozturkMSFT** [comment]
@dotMorten Glad to hear! Can you tell me your OS and PowerShell versions?

**Comment by bozturkMSFT** [comment]
@AR-May Let's print out a warning at the beginning that says TLS1.2 is required.

**Comment by vlada-shubina** [comment]
We agreed to put the note about TLS 1.2 in case download fails. 
Note should be similar too: "Ensure that TLS 1.2 or higher is enabled to use this script". 
Probably we can also reference https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#support-for-tls-12 or https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings to explain how to enable it. 
Should be done after or together with https://github.com/dotnet/install-scripts/issues/27.

**Comment by abrahamcuyong** [comment]
Just want to mention what saved my whole day solving this issue. This is just a temporary solution though. Hope it helps.

https://stackoverflow.com/a/47682111/12943500

**Comment by AR-May** [comment]
As agreed, added a message about TLS 1.2 when it is a reason of a download failure.

**Comment by TarasKuzBinariks** [comment]
> Just want to mention what saved my whole day solving this issue. This is just a temporary solution though. Hope it helps.
> 
> https://stackoverflow.com/a/47682111/12943500

Thank you!!!
