### ISSUE TITLE
Architecture `<alto>` not supported.

### ISSUE THREAD

**Issue by ricardoboss** [dotnet/install-scripts#92]
I am trying to install the dotnet runtime on an old version of linux running on a MIPS architecture. Is this even possible? Is there any version of dotnet which runs on MIPS?

**Comment by bozturkMSFT** [comment]
Hi @ricardoboss ,
 You can find all the supported operating systems together with the supporting SDK versions in the download table here: https://github.com/dotnet/installer#installers-and-binaries
 MIPS, unfortunately, is not supported.
